---
title: "7 hábitos de la gente altamente efectiva"
description: "Resumen con interpretación propia sobre el libro 7 hábitos de la gente altamente efectiva, de Stephen Covey"
description-meta: "Resumen del libro 7 hábitos de la gente altamente efectiva, de Stephen Covey"
author: "Leonardo Hansa"
date: "2023-07-20"
categories: [lecturas]
---

## Ideas introductorias

- Mapa y territorio. Un cambio de paradigma te puede ayudar a controlar mejor el territorio.
    + Mucha autoayuda falla porque enseñan un mapa sobre un territorio equivocado. Si estás usando un mapa que no se ajusta a tu territorio, no lo puedes aplicar. 
- Inside-out. Las victorias personales van antes que las públicas. Para mejorar las relaciones con los demás debes mejorar antes la tuya contigo mismo.

## 1. Sé proactivo

- El amor es un verbo. La gente proactiva se sacrifica por otros. 
- Aplicación:
    1. Durante un día fíjate en tu lenguaje y el de los demás. "Cuántas veces escuchas no puedo", "ojalá", "tengo que"...
    2. Identifica una experiencia con la que si te encuentras reaccionarías de manera reactiva. ¿Cómo la convertirás en proactiva?
    3. Elige un problema personal o profesional que te frustre. ¿Qué puedes hacer que ayude a mejorarlo.
    4. Durante treinta días trabaja en tu círculo de influencia con pequeños compromisos: no juzgues, no critiques, no discutas, no culpes. Trabaja en las cosas sobre las que tienes control.

## 2. Empieza con el final en mente

- En tu funeral van a decir unas palabras sobre ti. ¿Qué te gustaría que dijeran? ¿Cómo te gustaría que te recordaran?
- Empieza cada día con la imagen del final de tu vida, que ese sea tu criterio para evaluar tus acciones.
- Todo se crea en dos fases: una mental y otra física. Tú eres la segunda creación de tu propio diseño proactivo previo, o la segunda creación de los planes de otras personas, o circunstancias o costumbres pasadas.
- El hábito 1 es "tú eres el creador". El hábito 2 es la primera creación.
- Solemos necesitar más un destino y una brújula (conjunto de principios y direcciones) y menos una hoja de ruta. **El camino por delante no lo conocemos y necesitarás improvisar más de lo previsto.**
- Soy quien soy hoy por las decisiones que tomé ayer. 
- Cuando quieras ser efectivo, piensa de manera amplia. No tiene sentido que te centres en tu éxito profesional si dejas de lado tu salud.
- Piensa en tu visión a largo y misión en varios roles. Eso te dará balance

## 3. Pon primero lo primero

- Las personas exitosas tienen el hábito de hacer lo que los fracasados no quieren hacer.
- La gente poco efectiva dedica mucho tiempo a **cosas urgentes poco importantes** (en general, actividades con origen en otras personas). Luego desconectan un poco con actividades poco urgentes y poco importantes (Netflix...).
- No te hagas planes de organización diarios sino semanales.

## 4. Piensa en win/win

- Busca soluciones que beneficien a todas las partes involucradas. 
- Hay casos contrarios a eso: 
    - Hay incentivos para pensar en **win/lose**. La ley está motivada por el que hay un enemigo al que hay que     ganar, mediante abogados y juicios.
    - El **lose/lose** ocurre cuando se juntan dos personas cuyo objetivo es hacer que su enemigo pierda, aunque     sea a costa de su propio bienestar.
- **win/win or no deal.** Si no podemos llegar a un acuerdo en el que los dos salgamos beneficiados, es     mejor no cerrar acuerdo.
- la actitud de un individuo tiene dos dimensiones: valor y consideración. **Win/win** consiste en maximizar ambos.
- **Mentalidad de abundancia:** hay suficiente para todos.

## 5. Busca primero entender, luego ser entendido

- Imagina un óptico que recomienda a un cliente las gafas que tiene él, sin diagnosticar. 
- Historia del Padre que no escucha a su hijo...
- Las necesidades cubiertas no motivan.

## 6. Sinergiza

- Trabaja en equipo y crea sinergias para buscar equipos comunes. 
- Ejemplo de los fundadores de Apple

## 7. Afila la sierra

- Cuidar y mejorar continuamente los cuatro aspectos de tu vida: físico, mental, emocional y espiritual.
     + Queremos estar saludables pero no dedicamos 30 minutos al ejercicio. 
     + Queremos ser inteligentes pero no pasamos 20 minutos leyendo. 
     + **Trabajo, familia, relajación…**
- Cuatro dimensiones de control introspectivo: físico, mental, social y espiritual.
- Ejercicio de fuerza. Hay que apurar hasta el final porque es como el cuerpo sabrá que hay que regenerar fibras musculares más fuertes. Igual pasa con la paciencia.
- Aspecto espiritual: hay personas que encuentran en la inmersión en la música o literatura la misma satisfacción espiritual que otras personas en la meditación o en la lectura de escrituras sagradas.
- Prescripción médica: ve a un sitio que tengas buen recuerdo de niño. A las 9, escucha. A las 12, try reaching back (estudia el pasado). A las 3, explora tus motivos (si tus motivos están mal, entonces todo lo que haces está mal). A las 6, escribe tus preocupaciones en la arena.
- La lectura nos ayuda con el hábito de primero entender, ya que nos educa en el hábito de no poner nuestra autobiografía en medio de cada idea que nos llegue.
- Hans Selye: "una vida larga, sana y feliz es el resultado de hacer contribuciones "
- "Trata a una persona como es, y seguirá igual. Trata a un persona como puede ser, y llegará a ello" (Goethe)
