---
title: "Comparativa pequeña entre tidyverse y R base"
description: "Una comparativa entre algunos códigos en R base y tidyverse para tratar un data frame"
description-meta: "Una comparativa entre algunos códigos en R base y tidyverse para tratar un data frame"
author: "Leonardo Hansa"
date: "2023-12-07"
categories: [datos]
execute: 
  echo: false
freeze: auto
---

Me gusta leer [críticas contra tidyverse](https://github.com/matloff/TidyverseSkeptic). ¿Porque lo odio?

No, lo uso todo el rato. Todos los días. Mi trabajo se basa en [el tidyverse](https://www.tidyverse.org/).

¿Por qué leo críticas entonces?

Porque no entiendo que las haya. Así que me obligo a leer otros puntos de vista para ver en qué estoy equivocado.

Por ahora, gano yo. El link que publico al principio no es convincente. Un día le responderé al autor. Mientras tanto, estudio R base.

Me parece entretenido. Incluso bonito.

Y bromas aparte, le reconozco una cosa: **me quita toda la gestión de dependencias.** Cuando ejecuto este blog en GitHub Actions o cuando creo una librería, quitar dependencias simplifica mucho el trabajo y el proceso.

Eso sí me gusta de R base.

Pero para el día a día es un infierno.

Así que se me ha ocurrido hacerme un diccionario de R base y tidyverse, de cosas que consulto a veces.

Es un mini diccionario: faltarán muchas cosas aquí que te harán falta. Pero aquí encontrarás algunas que quizá te hagan falta. Y oye, si es así, tu búsqueda ha terminado.

## Conversión R base - Tidyverse

Para simplificar dependencias trabajaré, por supuesto, con `iris`.

+-----------------------------------------------------------------------------------------------+---------------------------------------------+------------------------------------------------------------------------------------------------------+
| **Operación**                                                                                 | **Tidyverse**                               | **R base**                                                                                           |
+-----------------------------------------------------------------------------------------------+---------------------------------------------+------------------------------------------------------------------------------------------------------+
| Calcula la media de una métrica por grupo.                                                    | `iris |>`                                   | `aggregate(`                                                                                         |
|                                                                                               |                                             |                                                                                                      |
|                                                                                               | `group_by(Species) |>`                      | `Sepal.Length ~ Species,`                                                                            |
|                                                                                               |                                             |                                                                                                      |
|                                                                                               | `summarise(mean(Sepal.Length))`             | `iris,`                                                                                              |
|                                                                                               |                                             |                                                                                                      |
|                                                                                               |                                             | `mean)`                                                                                              |
+-----------------------------------------------------------------------------------------------+---------------------------------------------+------------------------------------------------------------------------------------------------------+
| Extrae los números de un texto (aplica a cualquer patrón, como DNI, razón social, etc).       | `str_extract(`                              | `regmatches(`                                                                                        |
|                                                                                               |                                             |                                                                                                      |
|                                                                                               | `"cosa123cosa",`                            | `"cosa123cosa",`                                                                                     |
|                                                                                               |                                             |                                                                                                      |
|                                                                                               | `"\\d+")`                                   | `m = regexpr("\\d+", "cosa123cosa", perl = TRUE))`                                                   |
+-----------------------------------------------------------------------------------------------+---------------------------------------------+------------------------------------------------------------------------------------------------------+
| Quédate con las observaciones cuyo valor (en una métrica) sea mayor que la media de su grupo. | `iris |>`                                   | `do.call("rbind",`                                                                                   |
|                                                                                               |                                             |                                                                                                      |
|                                                                                               | `group_by(Species) |>`                      | `lapply(split(iris, iris$Species),`                                                                  |
|                                                                                               |                                             |                                                                                                      |
|                                                                                               | `filter(Sepal.Lengh >= mean(Sepal.Length))` | `function(df) {               subset(df, Sepal.Length >= mean(df$Sepal.Length)) }))`                 |
+-----------------------------------------------------------------------------------------------+---------------------------------------------+------------------------------------------------------------------------------------------------------+
| (\*) Pasa de formato ancho a formato largo - Transformación *melt* - Pasa métricas a filas    | `iris |>`                                   | `iris$id <- 1:nrow(iris)`\                                                                           |
|                                                                                               |                                             | `reshape(iris,`                                                                                      |
|                                                                                               | `pivot_longer(-Species)`                    |                                                                                                      |
|                                                                                               |                                             | `idvar="id",`                                                                                        |
|                                                                                               |                                             |                                                                                                      |
|                                                                                               |                                             | `direction="long",          varying=list(1:4),         v.names = "value",         timevar="metric")` |
+-----------------------------------------------------------------------------------------------+---------------------------------------------+------------------------------------------------------------------------------------------------------+

: Comparativa R base - Tidyverse

En la 4ª he puesto un asterisco porque está mal. No soy capaz de hacer eso en R base de una manera razonablemente cómoda para mí.

Pero yo lo sigo intentando.
