project:
  type: website

website:
  title: "Leonardo Hansa"
  description: "Tips sobre análisis de datos"
  favicon: favicon.png
  navbar: 
    background: "#ffffff"
    search: false
    pinned: true
    left: 
      - text: "Contenidos"
        href: "contenidos.qmd"
        icon: "book"
      - text: "Cu-cu-trás"
        href: "https://leonardohansa.com"
        icon : "balloon-heart"
    collapse: false
    collapse-below: "md"
  sidebar: false
  page-navigation: false
  page-footer: 
    right : 
      - text: "Legal"
    border: false
  cookie-consent: 
    type: express
    palette: light
    prefs-text: "Cookies"
  site-url: 'https://lhansa.github.io/'
  site-path: '/'
  
format:
  html:
    theme: 
      - default
      - custom.scss
    toc: false
    link-external-icon: false
    link-external-newwindow: false
    linkcolor: "#800080"
    execute: 
      echo: false
      message: false
      warning: false
    lang: es
    
execute: 
  freeze: auto
