---
title: "Pernotaciones por Comunidades Autónomas"
description: "Exploración de datos del INE de Pernotaciones por Comunidades Autónomas"
description-meta: "Exploración de datos del INE de Pernotaciones por Comunidades Autónomas"
author: "Leonardo Hansa"
date: "2024-08-04"
categories: [exploraciones]
execute: 
  echo: true
  message: false
  warning: false
freeze: true
---

El INE tiene unos datos de pernoctaciones a distintos niveles, mes a mes. Me interesan a nivel de Comunidad Autónoma.

```{r}
#| label: lectura
library(readr)
library(dplyr)
library(ggplot2)

ggplot2::theme_set(ggplot2::theme_light())

df_pernoctaciones <- read_csv2("2941 (1).csv", locale = locale(encoding = "latin1"))

df_pernoctaciones <- janitor::clean_names(df_pernoctaciones)
```

El formato de los datos nunca entenderé quién lo ha decidido. Imagino que alguien que no tenía que trabajar con ellos. Los proceso un poco.

```{r}
#| label: procesado
df_series <- df_pernoctaciones |>
  # Quito NAs porque son el total
  filter(!is.na(comunidades_y_ciudades_autonomas)) |> 
  mutate(
    periodo = paste0(periodo, "D01"), 
    periodo = as.Date(periodo, format = "%YM%mD%d"), 
    total = parse_number(
      total, 
      locale = locale(grouping_mark = "."),
      na = c(".", "..")
    )
  ) |> 
    group_by(comunidades_y_ciudades_autonomas, periodo) |> 
    summarise(pernoctaciones = sum(total, na.rm = TRUE), .groups = "drop")
```

Y aquí, la evolución de pernoctaciones mes a mes de cada Comunidad Autónoma:

```{r}
#| label: evolucion
#| fig-height: 30

formato <- scales::label_number(big.mark = ".", scale = 0.001, suffix = "k")
ggplot(df_series, aes(x = periodo, y = pernoctaciones)) + 
  geom_line(col = "#800080") + 
  geom_smooth(method = "loess") + 
  scale_y_continuous(labels = formato) + 
  facet_wrap(
    ~comunidades_y_ciudades_autonomas, 
    scales = "free_y", 
    ncol = 3
  ) + 
  labs(
    title = "Pernoctaciones mensuales por CCAA", 
    caption = "Fuente: INE", 
    y = "Pernoctaciones (miles)", 
    x = ""
  )
```


