---
title: "Rompe la barrera del no"
description: "Resumen del libro Rompe la barrera del no"
description-meta: "Resumen del libro Rompe la barrera del no"
author: "Leonardo Hansa"
date: "2022-09-11"
categories: [lecturas]
---


## 1. Las nuevas reglas

- Escuchar es la concesión menos costosa y más eficaz que podemos hacer.
- hay que discernir entre deseos (aspiraciones) y necesidades ( el mínimo acuerdo).
- Los seres humanos somos irracionales.
- La vida es negociar.

## 2. Sé un espejo

- Al entrar en una negociación, tu objetivo debe ser sonsacar toda la información posible. Si entras creyendo que ya lo sabes todo, la negociación no te saldrá bien.
- El fbi tenía equipos de escucha. Cada miembro se encargaba de entender una parte de la información sobre el secuestrador. Escuchar bien no es fácil porque nuestros sesgos nos llevan a buscar coherencia con nuestras asunciónws en lugar de la verdad.
- cinco pasos: uno, emplea un tono de locutor de radio de programa nocturno. Dos, empieza por un lo siento. Tres, usa el reflejo (repite las dos o tres últimas palabras de lo que dice tu interlocutor). Cuatro, mantén silencio después del reflejo. Cinco, repite.
- La negociación no es una batalla de argumentos sino un proceso de descubrimiento.
- La otra persona debe ser tu único centro de atención.
- Baja el ritmo, no te apresures.
- Sonríe. Incluso por teléfono te cambiará la voz (positivamente).
- Tres tonos de voz: locutor de radio (útil para dejar un argumento claro y crear autoridad), positivo/alegre (el genérico, hay que relajarse y sonreír) y asertivo (rara vez se usa).

## 3. No sientas su dolor. Etiquétalo

- Las emociones son el medio para llegar a la información, es decir, a lo que el interlocutor necesita.
- Igual que el psicólogo, tienes que hurgar en las emociones del paciente para hacer aflorar sus problemas. Luego devuelves la respuesta para que el paciente siga profundizando  y modifique su comportamiento.
- Hay que hablar poco y escuchar mucho.
- En una negociación te puedes hacer el tonto o responder “no entiendo”. Pero no puedes ignorar a la otra parte —disminuye las probabilidades de que hagan lo que queremos que hagan porque no se genera confianza.
- La **empatía** es la habilidad de reconocer la perspectiva de tu interlocutor y la vocalización de ese reconocimiento. O sea, escuchas a la otra persona, entiendes lo que le pasa y lo repites.
    - No es estar de acuerdo ni apoyar. Es comprender.
- La **empatía táctica** consiste en comprender sentimientos y estado de ánimo de otra persona y también escuchar lo que está detrás de esos sentimientos, de forma que puedas influir en lo que viene a continuación.
    - Es pensar desde el punto de vista de otra persona y evaluar sus motivaciones.
- Si de verdad prestas atención a lo que otra persona está diciendo, puedes llegar a saber con antelación lo que va a decir.
- “Hay que mostrar respeto incluso a los enemigos. Intentar comprender y, en la medida de lo posible, empatizar con sus perspectivas y sus puntos de vista.” (Hillary Clinton)
- Etiqueta las emociones de la otra persona. Usa frases indirectas como “Parece que…”, “suena a que”,”da la sensación de que…”.
- Es incómodo porque parece ofensivo pero la gente no se suele dar cuenta de lo que estás haciendo.
- Presta atención a los cambios (físicos, gestos, posturas) de otra persona ante tus palabras.
- Los videntes estudian el lenguaje no verbal de sus clientes ante preguntas vagas y de ahí extraen lo que quieren oír.
- Si tu interlocutor no está de acuerdo con la etiqueta no pasa nada. Reculas: “No quise decir que sea eso lo que sucede. Solo que lo parece.”
- Cuando exploras las objeciones con etiquetas, estas te permiten dar con la emoción primaria que causa el comportamiento de tu interlocutor. Esta emoción es la clave para resolver todo lo demás.
- Etiquetar los miedos hace que pierdan efecto.
- Decir "mira, soy un gilipollas" ante un error tuyo facilitará la interlocución con la otra persona.
- Los abogados defensores en su primera intervención enumeran todas las acusaciones y los puntos débiles que tendrán para defenderlo. Empiezan acentuando lo negativo (sacarse el aguijón).
- El primer paso es echarte en cara todas las cosas terribles de las que tu interlocutor pueda acusarte: autoacusación.

## 4. Cuidado con el “sí”. Domina el “no”

- Una trampa en la que muchos caen es en tomarse lo que dicen los demás en sentido literal.
- Un no es el comienzo de una conversación. Eliminas lo que no Interesa a tu interlocutor y eso te da más información que un sí falso o un quizá.
- Cuando dices no a una propuesta, estás más predispuesto a escuchar lo que te ofrecen porque ya Has dejado clara tu posición.
- Deberías ver el no como una decisión temporal, no suele ser una decisión racional, y sirve para mantener el status quo.
- En de entrada diga no, el autor plantea que tienes que dejar decir no al principio, ya que tu adversario quiere defenderlo a toda costa. Si se lo pones en bandeja al principio de la conversación, ya no le queda nada que defender.
- No" puede significar muchas cosas: aún no estoy preparado, Estás haciéndome sentir incómodo, no lo entiendo, no creo que pueda permitírmelo, quiero otra cosa, Necesito más información, quiero hablarlo con otra persona.
- Hay tres clases de sí: de engaño, de confirmación y de compromiso.
- Provoca un no con un correo: ¿se ha dado por vencido con este proyecto?

## 5. Cómo provocar las dos palabras que transformarán inmediatamente cualquier negociación

- Pasos para conseguir un "así es". 1. Pausas efectivas. 2. Pequeños alientos. 3. Reflejar, repetir. 4. Etiquetar ("parece que..."). 5. Parafrasear, para mostrar que se está entendiendo. 6. Resumir
- Cuando tu adversario dice así es, está aceptando tu discurso.
- Un así es es mejor que un sí.

## 6. Moldea su realidad

- En todas las negociaciones, el que parece el débil tiene siempre un punto de ventaja, porque todos tenemos puntos ciegos irracionales, necesidades ocultas y nociones inconscientes poco desarrolladas.
- Las fechas límites o la idea de lo justo puede hacer que una persona actúe de manera irracional y lo puedes aprovechar.
- No hagas concesiones. La idea de "buscar un término medio con el que todos ganen" no tiene sentido. Si quieres ir con zapatos marrones y tu pareja te recomienda negros, no te pongas uno marrón y uno negro.
- No hacer ningún trato es mejor que hacer un mal trato.
- Saber ceder se ha convertido en un bien moral.
- Nunca te comprometas a llegar a un punto medio.
- El tiempo juega un papel clave para ambas partes. Todos tendemos a actuar de manera impulsiva cuando se acerca el plazo, aunque haya sido decidido de manera arbitraria.
- Los plazos y las fechas límite son, con frecuencia, arbitrarios y casi siempre flexibles, y su incumplimiento rara vez desencadena las consencuencias que creemos que tendrá.
- Cuando los negociadores comunican sus plazos a la contraparte, consiguen mejores acuerdos.
- En una negociación no puedes pensar que el otro piensa como tú.
- Las decisiones van de la mano de las emociones. Antonio Damasio cuenta que personas con daños en la psrte del cerebro que se encarga de las emociones no pueden tomar decisiones. Pueden describir los pros y contras de una situación, pero no decidirse ante ella.
- Justo es una palabra muy poderosa. Tendemos a cumplir más acuerdos cuando sentimos que se nos trata justamente y tendemos a romperlos en caso contrario.
- Lo malo es que no valoramos si algo es justo de acuerdo con su valor, sino basándonos en sesgos. La aversión a la pérdida hace que perder 20 euros se sienta como más injusto que lo justo que verías ganar 20 euros.
- Que alguien te acuse de injusto hará que te sientas insultado. Este sentimiento, el sentirnos injustos, nos llevará a hacer concesiones irracionales.
- La frase "solo quiero lo que es justo" puede hacer que tu interlocutor ceda. Cuidado:puede usarse como manipulación. Si te la plantean, discúlpate por haber sido injusto en algo concreto o aplica el reflejo: ¿justo?
- "Quiero que sientas en todo momento que te estoy tratando de forma justa, así que te pido por favor que si en algún momento crees que no lo estoy haciendo, me lo digas, y veremos cómo resolverlo"
- Cuando tengas una propuesta, no puedes venderla con argumentos racionales sino llegando a los sentimientos de tu interlocutor. Una niñera no vende cuidado de los niños si una noche de relax para los padres.
- Aunque nuestras decisiones sean irracionales, existen patrones. En general, tiendes a dar más valor a un objeto si es tuyo que si lo tuviera otra persona.
- Para ganar ventaja en una negociación tienes que demostrar que la otra persona perderá algo si el pacto se rompe.
- Debes dejar claro que sabes qué emociones tendrá tu interlocutor si pierde la oportunidad que le brinda el pacto. Aunque el pacto sea malo, no quieren perder lo que obtendrían.
- Es mejor ceder a la otra parte la iniciativa en negociaciones económicas, en general. Depende de la cantidad de información que cada parte tenga sobre la otra.
- Ofrecer un rango en lugar de una cifra es más efectivo.
- No todo es dinero. Piensa si tu contraparte puede ofrecerte algo que les salga barato pero a ti te aporte, como publicidad.
- Números no redondos, como 34627, parece un presupuesto más inamovible que 35000.
- Pregunta para una entrevista de trabajo, después de haber convencido a tu interlocutor de que serás un representante de sus ideas: qué hace falta para tener éxito aquí?
- Estás técnicas tienen sus retractores porque parecen manipulación. Son técnicas que de manera racional aprovechan la parte irracional de nuestras decisiones. Es la única forma de moldear la percepción de los demás.
- El valor real de cualquier cosa depende del punto de vista del que lo observe.

## 7. Crea una ilusión de control

- La negociación no es un combate en el que nunca debas recular.
- La clave en la negociación es que la otra persona llegue a sugerir la solución que a nosotros nos vale.
- Tienes que hacer creer a tu oponente que es él quien controla la negociación.
- No intentes hacer que el otro crea lo mismo que tú. Intenta anular su insistencia en no aceptar lo tuyo, pero sin convencerlo de manera directa.
- la mejor forma de montar a caballo es dirigirse en el sentido que quiera ir él.
- Haz que el oponente sienta que tiene el poder con preguntas que sirvan para pedir su ayuda.
- Preguntas con un planteamiento adecuado pueden convertir peticiones tuyas en dudas para las que necesitas la ayuda de tu interlocutor. Una pregunta puede hacer que tu interlocutor sienta que un problema tuyo es también suyo.
- No deben permitir respuestas cerradas del tipo sí o no. Hay que usar preguntas del tipo wh periodístico. Las prioritarias son qué, cómo y por qué. Cuidado con la última porque a veces esconde una acusación. Funciona por ejemplo en "por qué ibais a cambiar vuestro proveedor de siempre para probar con nosotros?"
- por qué hiciste esto se puede cambiar a qué te movió a hacer esto.
- en qué sentido esto es algo importante para ti
- cómo puedo contribuir para hacer que esto sea mejor para ambos?
- cómo te gustaría que procediera?
- qué es lo que nos ha conducido hasta esta situación?
- cuál es el objetivo?
- cómo se supone que voy a conseguir eso?
- implícitamente, debes convencer a tu interlocutor a base de preguntas que quieres lo mismo que él pero necesitas de su inteligencia para conseguirlo.
- Es imprescindible que controles tus emociones. Si no, cualquier técnica será en vano.
- No contraataques. Responde a un ataque con una pregunta abierta.
- El control de una conversación no lo tiene quien habla sino quien escucha.

## 8. Garantiza la ejecución

- Llegar a un acuerdo no sirve de nada si la ejecución del mismo no está bien planteada.
- preguntas de cómo harán que la contraparte tenga que pensar en esa ejecución y ayudará a que crea que la solución final es idea suya.
- Las personas se esfuerzan más en llevar a cabo ideas que consideran suyas.
- La negociación es el arte de hacer que los demás se salgan con la tuya.
- Dos preguntas: cómo sabremos que vamos por el buen camino? Qué haremos si vemos que la cosa se tuerce? Cuando respondan, resume con tus palabras para obtener un así es.
- Que te digan tienes razón o lo intentaré son signos de que te están dando la. Razón como a los tontos, sin compromiso.
- Muchas veces las negociaciones no tienen tanto que ver con ganar o ahorrar un dinero sino con autoestima y estatus.
- Es importante entender al resto del equipo, aunque tú solo hables con tu interlocutor: "cómo afecta esto a los demás?"
- Presta siempre atención al tono de voz y, sobre todo, al lenguaje corporal. Si no se corresponden con el mensaje, seguramente sea porque es mentira.
- Etiquetar lo que ha dicho el otro (parece que) ayudará a confirmar si es mentira.

## 9. Regateo

- tres perfiles de negociador: acomodador, asertivo y analista.
- Los analistas son minuciosos y detallistas pero pueden resultar fríos. Si eres analista, sonríe al hablar. Si hablas con un analista, plantea pocas preguntas de golpe y proporciona datos.
- Los acomodadores disfrutan con la relación. Pueden ofrecerte algo que no pueden cumplir simplemente por caer bien. Cuidado con el exceso de cháchara si eres uno.
- Un asertivo es directo y quiere que se le entienda. Hazle saber que entiendes lo que dice. Si eres uno, seguramente suenes brusco a los demás
- En silencios, el acomodador cree que el otro se ha enfadado, el asertivo se pone a hablar y el analista intenta pensar.
- La paradoja del normal soy yo: los demás deben ver el mundo como lo veo yo.
- El enfado puede darte ventaja si tu reacción es comedida y real. Si results fingido, será contraproducente.
- Usa el por qué solo cuando cuestiones algo que realmente favorecen, como por qué cambiarías a tu proveedor actual.
- Nos gusta más 1,99 que 2, incluso aunque sepamos que es un truco.

## 10. Encuentra el cisne negro

- En una negociación habrá cosas que no sabes que no sabes. Eso puede dar ventaja a tu interlocutor.
- hay tres tipos de ventaja: ventaja positiva (tienes algo que tu interlocutor quiere), negativa (cuando puedes amenazar; puede usarse de manera legítima con etiquetas como parece que no te importa dejarme en esta situación) y normativa (te apoyas en las creencias de la otra persona y aprovechad que nadie quiere ser hipócrita)
- Paradoja del poder: cuanto más presionas, más fácil es que encuentres resistencia.
- Principio de similitud: confiamos más en las personas similares a nosotros. Eso se debe a que la similitud puede conllevar una capacidad de entendimiento mayor.
- Las personas tienden a aceptar más una propuesta tuya si saben que hay una razón concreta detrás de ella.
- Cuando tu interlocutor haga algo irracional, que te parezca una locura, piensa que igual no entiendes bien su situación.
- Elimina el miedo al conflicto. El conflicto es una herramienta para conseguir lo que quieres.