---
title: "12 reglas para la vida"
description: "Resumen con interpretación propia sobre el libro 12 reglas para al vida, de Jordan Peterson"
description-meta: "Resumen sobre el libro 12 reglas para la vida, de Jordan Peterson"
author: "Leonardo Hansa"
date: "2023-07-19"
categories: [lecturas]
---

_Comentario mío: el libro no me ha gustado. Creo que está mal planteado, porque tiene conceptos interesantes pero muy mal hilados. Pero eso: tiene conceptos interesantes. De algún capítulo no hay notas o bien porque me parecía una tontería o bien porque no tenía nada a mano para apuntar. Y algunas de las notas son frases literales, otras son reinterpretadas; con algunas estoy a favor, con otras estoy en contra, y otras me han llamado la atención pero no me he posicionado (aún)_

## Introducción

- La pérdida de creencias grupales lleva a una vida caótica. Y la presencia de creencias grupales lleva a conflictos con otros grupos.
    + En occidente llevamos tiempo reduciendo nuestra tradición, religión y sentimientos nacionales, en parte para evitar los conflictos grupales. Pero así cada vez tendemos más a a vidas sin sentido, ni valores.
- la serotonina da una postura de victoria a las langostas. La octapina, de derrota.
- ley de price, para distribución financiera y creativa
- Mateo 25:29: para los que tenéis todo, se os dará más; para los que no tienen nada, todo se os quitará
- la tradición oral religiosa tiene más un fin moral que un fin descriptivo


## Regla 1. Enderézate y echa los hombros hacia atrás

- Una langosta victoriosa tiene una postura más amplia. Y mayor proporción de serotonina que de octopamina. Inyectar serotonina en una langosta derrotada hace que cambie su postura.
- Las hembras dejan que los varones se peleen y luego eligen entre los más fuertes. 
    + Confían en que el comportamiento de estos se calme. 
    + Es un esquema llevado a la Bella y la Bestia o 50 sombras de Grey.
- La naturaleza selecciona pero no es un concepto estático. 
    + "En mi reino tienes que correr con todas tus fuerzas para no quedarte en el mismo lugar" (Reina, Alicia en el País de las Maravillas)
- Atrévete a ser un peligro
- Erguirse significa aceptar voluntariamente la carga del Ser.
- Si te presentas físciamente como alguien derrotado, la ente te tratará como alguien derrotado. Y te sentirás como tal. 
- Si comienzas a erguirte, la gente te mirará como a tal.

## Regla 2. Trátate a ti mismo como tratarías a alguien que depende de ti

- El equilibrio entre caos y orden es importante para no frustrarnos pero que haya algo de motivación. Algo de riesgo. 
- El orden puede descontrolarse y convertirse en una migración forzosa o un campo de concentración. 
- El caos se relaciona con lo femenino. Todo se origina en el desorden y todos nos originamos en una madre. 
- Incluso el jardín del Edén tenía una serpiente porque toda calma tiene un punto de caos, como el punto negro en la serpiente blanca tahoista.
- siempre hay un enemigo. Incluso aunque derrotáramos a todos, estaríamos nosotros mismos.
- Es mejor enseñar a quienes dependen de ti a que sean competentes que protegerlos demasiado.
- Nuestra vista (aguda) nos permite identificar rápidamente los frutos maduros de los árboles, que son los comestibles.
- igual que pensamos mal de otras personas, hay personas que de quienes realmente piensan mal es de sí mismas.
- Alguien que tiene un porqué tendrá casi siempre un cómo (Nietzsche)


## Regla 3. Hazte amigo de aquellos que queran lo mejor para ti

- Freud: compulsión de repetición. Gente que no tiene buena impresión de sí misma, busca rodearse del mismo tipo de personas que en el pasado le hicieron algún mal. Consideran que no merecen nada mejor.
- La gente suele aceptar o incluso magnificar su propio sufrimiento, o incluso el de los demás , si lo pueden presentar como demostración de las injusticias del mundo.
- Cuando metes en un grupo civilizado (un equipo de trabajo, reclusos organizados) a una persona más rebelde, el grupo no influye en el individuo, sino al revés, y el grupo empeora sus hábitos. Es más fácil ir hacia abajo.
- Cuando ayudas a alguien, ¿lo haces porque quieres ayudarlo? ¿O porque quieres demostrar lo bondadoso que eres?
- Hay quien se rodea de gente irresponsable porque en comparativa ellos están mejor. Es una comparativa fácil para hacerte creer especialmente bondadoso.
- Si tienes un amigo que no lo recomendarías a tu hermana, a tu padre o a tu hijo, ¿por qué lo tienes tú?

## Regla 4. No te compares con otro, sino con cómo eras tú antes

- En el mundo rural es más fácil destacar porque hay menos personas que en las ciudades.
- hay sobrerrepresentación de personajes famosos nacidos en pueblos.
- Tiempos de espuma de pomelo y helado de whisky con tabaco.
- "siempre habrá alguien mejor que tú" es un tópico nihilista. No aporta información esa frase.
- la religión se encarga de lo que es correcto. Un religioso buscará hacer lo que es correcto, lo que está bien, aunque eso simplemente sea ser obediente.
- Que tu te creas algo, que te etiquetes en una identidad, no significa que lo seas. Tus acciones dicen qué eres. Y eres demasiado complejo para entenderte a ti mismo.
- La Biblia como documento escrito durante mucho tiempo por muchos y nadie.
- Presta atención a lo que molesta:
    + ¿Qué me molesta?
    + es algo que podría arreglar?
    + estaría verdaderamente dispuesto a arreglarlo?
    + si alguna respuesta es no, busca molestaias en otro lado.
- No sobrestimes tu conocimiento de ti mismo.
- Pregúntate "qué podría hacer y estoy dispuesto a hacer para que me vida sea un poquito mejor?". Puede ser algo tan básico como una gestión pendiente. O si crees que un tarea te va a llevar media hora y no te pones porque es mucho tiempo, dedícale 5 minutos hoy. Ayudará a que la veas como algo más asequible.
- La vida no tiene el problema; lo tienes tú. Si la vida no te va bien, quizá es tu conocimiento lo que resulta insuficiente. Quizá tu estructura de valores necesita una remodelación. Quizá lo que quieres e ciega y no te deja ver oras posibilidades. 

## Regla 6. Antes de criticar a alguien, asegúrate de tener tu casa en perfecto orden

- Cuando te das cuenta de las injusticias del mundo, puedes ignorarlo, puedes bucar el placer, puedes resignarte y aceptarlo o puedes tomar medidas y suicidarte.
- A la gente le sorprende que haya tantas masacres en EEUU o similares, pero es el primer acontecimiento narrado según la Biblia.
- Tolstoi entiende que no hay otra escapatoria que el asesinato para combatir las injusticias "el bien de los muertos es mejor que el bien de los vivos"
- los asesinos de masacres (y Caín) asesinan para contrariar el sistema, porque el mundo es injusto en sí mismo.


## Regla 7. Dedica tus esfuerzos a hacer cosas con significado, no lo que más te convenga 

- La vida es sufrimiento.
- "No tentaraás al señor tu Dios" ( Mateo 4:7) No renuncies a tu responsabilidad. No pidas que una tercera persona intervenga en tu favor cuando tú tienes margen de acción y no lo estás aprovechando.
- el socialismo se motiva más por una motivación de odio a los ricos y triunfadores más que en un verdadero interés por los pobres.
- los socialistas creen en el dinero igual que los capitalistas y acaban siendo capitalistas.
- Dios castigó al humano echándolo del Edén y condenándolo a trabajar. 
- A veces cuando las cosas van mal, elproblema viene de cómo interpretas las cosas. 
- Si el mundo que ves no es el que quieres, revisa tus valores.
- Es hora de que sacrifiques lo que más quieres para convertirte en quien quieres convertirte y dejar de ser quien eres.

## Regla 9. Da por hecho que la persona a la que escuchas sabe algo que tú no sabes

- Cuando participas en una verdadera conversación, hablas y escuchas, pero sobre todo escuchas.
- Puedes ser bastante listo si te limitas a callarte. 
- No sabemos escuchar. Tendemos a evaluar porque escuchar es peligroso. Puede cambiarte (Carl Rogers) 
- regla: cuando estés en una discusión, antes de aportar una idea tuya o una opinión, tienes que repetir la idea anterior que ha dicho la otra persona, para que ella valide si lo has entendido bien.
- Al escuchar, permites que la otra persona piense. La primera vez que alguien expone algo en voz alta, llega a contradicciones y tiene que orientarlas, deciendo qué olvida de sus anécdotas para dejar claros sus sentimientos. 
- si una conversación te resulta aburrida, es que no estás escuchando.
- la gente organiza su cabeza conversando

## Regla 10. Cuando hables, procura expresarte con precisión

- Los objetos como extensión de un sistema, de un árbol con ramas u hojas. No pasa nada porque se rompa un objeto, porque el sistema sigue en pie.
- tú no acabas en lo que acota tu piel. Llegas más allá. Si usas una herramienta, pasa a formar parte de ti y la usas como si sintieras con su extremo. Tu familia o amigos forman parte de ti (¿qué prefieres perder: un brazo o un ser querido?). Tus niveles de testosterona varían si tu equipo pierde o gana.
- Cuando usas una herramienta, no hace falta que la entiendas: solo te hace falta saber con precisión qué quieres hacer con ella.
- Somos más conscientes de nuestras limitaciones cuando algo que siempre usamos deja de funcionar y no lo sabemos arreglar, como un coche u ordenador. Simplificamos el mundo en el día a día.
- El mundo es fácil mientras es simple, y eso solo ocurre cuando ignoramos cómo funciona. Ante una catástrofe, un desastre, o un simple desajuste, nos damos cuenta de que nuestra percepción era equivocada. 
- Si no hay una tradición consesuada de quién hace qué, se acaba en tres escenarios. La esclavitud, en la que el esclavo se acaba revelando y llega el caos; la tiranía, en la que el tirano se aburre por exceso de obediencia y abandona al subordinado a su propia suerte; o la negociación. Esta exige que ambos jugadores hablen con franqueza y admitan que hay un problema. 
- vivir significa realizar una labor constante de mantenimiento
- las relaciones pueden acabarse por problemas que nunca nos atrevemos a solucionar ni siquiera plantear. 
- Nos negamos a ser específicos con un problema porque el serlo signfica admitir su existencia.
- si no eres específico, no solo no defines el triunfo, sino que tampoco defines tu fracaso. Pero eso en sí mismo está abocado al fracaso.


## Regla 11. Deja en paz a los chavales que montan en monopatín

- Los que patinan no se ponen protección porque no buscan la falsa seguridad de un equipo protector, sino la seguridad mediante la competencia.
-  Según Orwell, el socialismo en reino unido estaba representado políticamente por unas personas que no defendían a la clase obrera, sino que odiaban a los ricos.
-  Los chicos actualmente tienden a ser etiquetados de peores estudiantes que las chicas y menos simpáticos y más desobedientes. Pero también más independientes y menos susceptibles a la depresión. Los intereses de los chicos tienden a relacionarse con cosas, y los de las chicas con personas.
-  Estas diferencias están influidas por razones biológicos.
-  Políticas igualitarias como intentar que dos personas con el mismo trabajo cobren igual tienen la dificultad de decidir qué significa que dos trabajos sean iguales.
-  hay políticas que buscan que se eduque igual a los chicos que a las chicas, con la idea de que sean menos violentos. Pero la violencia a veces es innata. Y además hay mujeres que el psicólogo les recomienda ser más violentas, porque un exceso de simpatía hace que te seas demasiado servicial y te afecta en la autoestima.

## Regla 12. Si ves un gato por la calle, acarícialo

- Somos frágiles. Tenemos que aceptarnos y querernos entre nosotros con nuestras limitaciones sin intentar corregir. 
- ¿Qué le falta a un ser omnisciente, omnipresente y omnipotente? Limitación. Si uno no tiene limitaciones, consigue todo, y entonces no tiene una historia. La limitación te da una historia. 
- "En una vasija, es su interior vacío lo que la hace útil. En una ventana, es su interior vacío lo que la hace útil. Lo que hay es provecho; lo que no hay, útil." (Lao Tse)

