---
title: "El sutil arte de que todo te importe una mierda"
author: "Leonardo Hansa"
date: "2022-08-05"
categories: [lecturas]
---


> Manson’s idea of “kill yourself” is similar to Paul Graham’s idea of “keep your identity small.” The central point is that if you don’t have an identity to protect, then change becomes much easier. (James Clear)

## 1. No lo intentes

- Sutileza 1. Que algo te importe una mierda no significa ser indiferente, signifca estar cómodo siendo diferente
- Sutileza 2. Para que la adversidad te importe una mierda, primero debe importante algo diferente de la adversidad.
    + Cuando una persona no tiene problemas, la mente automáticamente encuentra la forma de inventarse alguno.
- Sutileza 3. Siempre estás eligiendo qué es importante para ti.
- La gente no se da cuenta de que es normal que las cosas, a veces, estén mal.

## 2. La felicidad es un problema

- El dolor y la pérdida son inevitables así que no deberíamos resistirnos a ellos.
- El sufrimiento es útil biológicamente para inspirar el cambio.
- la mente no distingue mucho entre dolor psicológico y dolor físico.
- La solución a un problema es simplemente la creación del siguiente.
- La felicidad se consigue resolviendo problemas, no evitandolos.
- con la negación no aceptas que tienes problemas cuya solución dará felicidad.
- con el sentimiento de víctima niegas que tus problemas tengan solución y culpas a otros de ellos.
- concepto de la caminadora hedónica: buscamos cambios pero nunca nos sentimos diferentes.
- qué dolor deseas en tu vida? Por qué estás dispuesto a luchar?

# 3. Tú no eres especial

- La gente que se cree con derecho a todo necesita encontrarse bien consigo misma. Ven cada situación como una razón o una amenaza contra su grandeza.
- una persona con autoestima real analiza sus aspectos negativos y actúa para mejorar
- El problema no es las cosas terribles que ocurren, sino las cosas terribles que se deben decir y no se dicen.
- Si tenemos problemas que no se pueden resolver, nuestro inconsciente cree que somos singularmente especiales o bien singularmente defectuosos; que no nos parecemos a nadie y que las reglas funcionan distinto con nosotros. En otras palabras, nos creemos con derecho a todo.
- Tanta información online nos hace creer que lo excepcional es la nueva norma, con lo que concluimos que somos gente del montón, no somos lo suficientemente buenos. Así que nos creemos con derecho a todo y lo compensamos con adicciones.
- La tecnología ha resuelto antiguos problemas económicos pero ha traído nuevos problemas psicológicos, como inseguridad, falta de confianza en uno mismo y vergüenza.
- Se ha transmitido que todos somos extraordinarios. Por lo que sentirse del montón sabe a fracaso.
- Como todos persiguen sen extraordinarios, algunos buscan destacar yendo al otro extremo: haciéndose ver como miserables y oprimidos.
- Muchas personas temen aceptar su mediocridad porque creen que si lo hacen, nunca llegarán a nada. Si no aceptas la mediocridad, acabas creyendo que la mayoría de vidas no vale nada (con las consecuencias).
- Quien es excepcional es por su obsesión por la mejoría. Y esa obsesión viene de aceptar que se es mediocre y buscar formas de ser mejor.
- gran parte de tu vida será aburrida y no notable. Y está bien.

## 4. El valor del sufrimiento

- el sufrimiento se soporta si tiene una causa, si sirve para una causa de fuerza mayor
- Hay capas de autoconciencia:
    - Qué siento.
    - Por qué lo siento. Estas preguntas destacan qué identificas por éxito o fracaso
    - Valores personales. Por qué considero X un éxito? Por qué considero Y un fracaso? BAjo qué estándar me evalúo? Y bajo cuál juzgo a quienes me rodean?
- Los problemas serán inevitables pero el significado de cada problema no lo es.
- De manera instintiva, nos comparamos con otros y vivimos para el estatus. Pero la cuestión real es bajo qué estándar nos medimos a nosotros mismos.
- En función de tus valores, incluso bajo unas mismas circunstancias, puedes ser un fracaso o un éxito.
- Pete Best: batería de los Beatles antes que Ringo, a quien despidieron antes de grabar love me do. Después de años de depresión, acabó diciendo que nunca habría sido tan feliz como ahora si hubiera seguido en los beatles. Porque ese despido contribuyó a que conociera a su mujer y tuviera hijos. Sus valores de lo que signfica el éxito cambiaron.
- Valores mediocres:
    - Placer. Lo más fácil de obtener y lo más fácil de perder. Nos venden placer todo el rato. El placer no es la causs de la felicidad, sino su consecuencia.
    - Éxito material. A más éxito material, menos valor tiene (10000 euros no valen igual para alguien que vive en la calle que para alguien que gana 50000). Y el éxito material se convierte en prioridad sobre valores como Honestidad, no violencia y compasión.
    - Tener siempre razón. Eso no permite aprender de tus errores
    - Mantenerse siempre positivo. La vida a veces es una mierda y es mejor aceptarlo. Las emociones negativas hay que expresarlas y hay que manifestarlas alineadas con nuestros valores
- Algún día en retrospectiva los años de más esfuerzo te parecerán los más hermosos (Freud) algunos de los mejores momentos en nuestra vida no son placenteros, no son exitosos, no son reconocidos y no son positivos
- Los buenos valores se basan en la realidad, son socialmente constructivos y son inmediatos y controlables.
    - Si tu parámetro es la popularidad, tu éxito se basa en que los demás te consideren popular, algo que no depende solo de ti, no lo puedes controlar.
- La mejora personal consiste en priorizar tus valores, elegir las mejores cosas en las que centrar tu atención. Mark Manson propone 5:
    - eres responsable de todo lo que te pasa,
    - vive en incertidumbre,
    - acepta el fracaso,
    - acepta el rechazo (di no)
    - contempla la mortalidad.

## 5. Siempre decides algo

- A veces, la diferencia entre un problema doloroso y la sensación de poder es la percepción de que nosotros lo escogimos, que somos responsables de ello.
- Somos reponsables de todo en nuestras vidas, sin importar las circunstancias externas. No siempre controlamos lo que nos sucede, pero siempre controlamos cómo interpretamos lo que nos sucede.
- Siempre somos responsables, es imposible no serlo. Si elegimos no responder a los eventos, Es una forma de responder a los eventos.
- La responsabilidad y la culpa no deberian ir siempre de la mano. Si alguien abandona un bebé a la puerta de tu casa, no es culpa tuya, pero es responsabilidad tuya el decidir qué hacer con el bebé.
- Culpa es tiempo pasado; responsabilidad es tiempo presente.
- Reconocer tus errores quizá te ayude a no verte como la víctima inocente que crees ser.
- Nos encanta asumir la responsabilidad de nuestros éxitos pero es más importante y más Fructífero aceptar la responsabilidad de nuestros fracasos. Simplemente culpar a los demás es hacerte daño a ti mismo.
- La intensidad del evento no cambia la verdad. Si tu hijo muere, o te atracan, o un gobierno extremista atenta contra los derechos, no es tu culpa pero sí eres responsable de tus actuaciones y tus emociones ante ello.
- El juego de la vida consiste en qué elecciones tomamos con las cartas que nos tocan, no en quejarnos sobre esas cartas.
- Victimismo chic: echar la culpa a otro grupo de mis desgracias. Todos los grupos se victimizan a sí mismos.
- Cuantas más personas se proclaman víctimas, más difícil es detectar a las verdaderas víctimas.
- Vivir en sociedad libre y democracia consiste en compartir la vida con otras opiniones, que quizá no te gusten. Ese es el precio.

## 6. Te equivocas respecto a todo

- No deberíamos buscar certeza sino duda. Duda de nuestros valores y creencias. Es la única forma de crecer. No deberíamos dedicar el tiempo a explorar en qué estamos acertados sino en qué estamos equivocados.
- Experimento. Persona en una habitación con botones. Si hacen una tarea concreta (desconocida para ella), una luz destella y ganan un punto. Tienen que ganar tantos puntos como puedan en 30 minutos. Una vez consiguen un punto, la tarea ya no funciona y tienen que buscar la siguiente, cada vez más complicada, con secuencias complejas o pulsar a la pata coja. Pero no hay patrón real: las luces son aleatorias. La gente hace algo complicado porque creen que es necesario, pero no sirve de nada.
- Tendemos a encontrar patrones donde no los hay porque relacionar cosas nos simplifica el entendimiento. Pero hay dos problemas:
    1. que el cerebro se equivoca observando y escuchando. Y recordando.
    2. una vez creamos un significado, nos cuesta desprendernos de él.
- Todas nuestras creencias están equivocadas: algunas están menos equivocadas que otras.
    - *me recuerda a George Box y su "todos los modelos están mal, pero algunos son útiles."*
- La gente mala no cree que sea mala: está segura de que los demás son malos.
- Cuanta más certezas buscas tener sobre algo, más inseguro te sientes. Cuanto más abierto estes a la ignorancia ante algo, más cómodo estarás con esa incertidumbre.
- La incertidumbre ayuda a que no nos juzguemos a nosotros mismos: no sabemos cómo de exitosos podemos llegar a ser y la manera de averiguarlo es probando.
- cuanto más amenaza algo cambiar cómo te percibes, lo exitoso o fracasado que te consideres, lo seguro que te consideras de estar a la altura de tus valores, más evitarás decidirte a hacerlo. Por eso la gente tiene miedo al éxito (igual que al fracaso): el éxito puede cambiar quién eres.
- Conocerte a ti mismo puede ser peligroso. Es mejor que nunca te conozcas: así nunca estarás anclado a una personalidad a la que ser fiel.
- el budismo defiende que te liberes. Me recuerda a Cohen. Cuando no nos contamos historias a nosotros mismos, nos liberamos para actuar.
- no te compares con identidades raras, porque te sentirás único y excepcional. Compárate con conceptos amplios y mundanos.
- preguntas pro incertidumbre:
    1. Y si estoy equivocado? Todos somos los peores observadorrs de nosotros mismos.
    2. Qué supondría si estuviera equivocado? Considerar un pensamiento sin aceptarlo es la marca de una persona educada (Aristóteles)
    3. Estar equivocado crearía un problema mejor o peor que el actual?
- si parece que eres tú contra el mundo, seguramente seas tú contra ti mismo

## 7. El fracaso es un paso hacia adelante

- solo podemos ser exitosos en algo en lo que estemos dispuestos a fallar.
- los mejores valores están orientados a procesos. Si cumples con tu propósito, se te acaba el valor, ¿y ahora qué? Así llegan las crisis, pprque te has quedado sin propósito en la vida.
- el miedo, la ansiedad, la tristeza pueden representar el dolor necesario para cambiar y crecer psicológicamente.
- La acción no es solo efecto de la motivation. También es causa de ella. Principio Haz algo.
- Lo importante para conseguir resultados es hacer algo, lo que sea, independiente del resultado. El fracaso no importará en ese caso, porque el objetivo es solo hacer algo. Y eso nos dará la motivación para seguir adelante.

## 8. La importancia de decir no

- El significado en la vida se basa en el rechazo de alternativas, la supresión de libertad: el compromiso a un estilo de vida, a una persona...
- Se nos ha convencido de que hay que estar abierto a todo, decir sí a todas las oportunidades. Pero necesitamos rechazar, porque necesitamos tener una postura favorable hacia algo. Si aceptamos todo, no nos dedicamos honestamente a algo, y nos sentiremos vacíos.
- Para apreciar algo, necesitamos rechazar activamente todo lo contrario a ese algo.
- Nos quedamos con relaciones que no nos dan felicidad, trabajos que nos queman, nos quedamos con ganas de decir lo que pensamos. Para ser honestos, tenemos que estar a gusto diciendo y escuchando "no"
- El rechazo contribuye a la mejora.
- no debes responsabilizar a los demás de tus problemas pero tampoco debes responsabilizarte de los problemas de los demás.
- en una relación enfermiza, cada uno intenta resolver los problemas del otro. Para sentirse así a gusto consigo mismos.
- La honestidad es más importante que sentirse bien todo el rato.
- cuantas más elecciones nos den, menos satisfechos estaremos con nuestra decisión.
- Si elegimos una opción pero dejamos puertas abiertas al cambio, por si acaso, no profundizaremos suficiente en nuestra decisión. Y estaremos siempre insatisfechos. Si nos comprometemos con nuestra decisión y nos olvidamos de las demás, aunque rechacemos oportunidades el compromiso nos hará aprovechar totalmente nuestra decisión.
- Cuando pasas por muchos trabajos, muchas relaciones, muchas posesiones, muchos pasatiempos, el siguiente te aporta ya poco.
- El compromiso es libertad y liberación.

## 9. Y luego te mueres

- ¿Por qué te importa la muerte si tienes tanto miedo a la vida?
- Becker: la negación de la muerte.
- Mark Twain; una persona que vive plenamente está siempre preparada para la muerte.
- ¿Cuál es tu legado? Cómo de mejor y diferente será el mundo cuando hayas muerto?
- Vas a morir y será porque fuiste afortunado para vivir.

## Léelo

- [Versión papel](https://www.amazon.es/SUTIL-ARTE-IMPORTE-MIERDA-HARPERCOLLINS/dp/8491392289?keywords=el+sutil+arte+de+que+casi+todo+te+importe&qid=1659696459&sprefix=sutil+arte%2Caps%2C135&sr=8-1&linkCode=ll1&tag=lhansa-21&linkId=e84a1d935eb8609e01d35a3f389e55c9&language=es_ES&ref_=as_li_ss_tl)
- [Versión kindle](https://amzn.to/3Qp7ytV)
