---
title: "27 aforismos de Nassim Taleb"
description: "Selección de aforismos de Taleb, del Lecho de Procusto"
description-meta: "Selección de aforismos de Taleb, del Lecho de Procusto"
author: "Leonardo Hansa"
date: "2022-09-03"
categories: [lecturas]
---

Selección personal de aforismos de [Nassim Taleb,](https://longitudsinanchura.com/2021/10/01/asalariado-taleb-habla-de-ti/) publicados en _El Lecho de Procusto._

1. La gente está mucho menos interesada en lo que tratas de mostrarle que en lo que tratas de esconder.
4. El trabajo te destruye el alma invadiéndote furtivamente el cerebro durante las horas que oficialmente no dedicas a trabajar. Sé selectivo con las profesiones.
6. No hay un estado intermedio entre el hielo y el agua. Pero sí lo hay entre la vida y la muerte : un empleo.
7. Nadie quiere ser completamente transparente; no para los demás y, desde luego, no para sí mismo.
8. Francia se hizo con Argelia confiando en que el país comiera cassoulette y resulta que, ahora, Francia come cuscús.
9. Preguntamos "¿por qué la crisis es tan profunda?" y no "¿por qué la crisis no es más profunda?"
10. [Dejar que otros ganen las batallas pequeñas es una manipulación muy poderosa.](https://longitudsinanchura.com/2022/09/11/rompe-la-barrera-del-no/)
11. Me pregunto cuántas personas buscarían riqueza excesiva si no conllevara una métrica de estatus.
12. La diferencia entre amor y felicidad es que los que hablan de amor tienden a estar enamorados y los que hablan de felicidad tienden a no ser felices.
14. A la larga es más fácil que te engañes a ti mismo que engañes a otros.
15. Hay dos clases de personas: las que intentan ganar discusiones y las que intentan ganar. Nunca son las mismas.
16. La burocracia es una construcción diseñada para maximizar la distancia entre quien toma las decisiones y los riesgos de una decisión.
17. Las tres adicciones más perjudiciales son la heorina, los carbohidratos y un sueldo mensual.
18. Me pregunto si un león o un caníbal pagaría un recargo elevado por un humano criado en libertad.
19. Una heurística sobre si tienes el control de tu vida: ¿puedes echarte siestas?
20. Uno de los libros más breves que he leído tenía 745 páginas. El libro más largo que he leído tenía 205 páginas.
21. Sea cual sea el tema, si no sientes que no sabes lo suficiente es que no sabes lo suficiente.
22. La tragedia es que gran parte de lo que consideras aleatorio está bajo tu control y, lo que es peor, también sucede la inversa.
23. Mi mayor problema con la modernidad quizá resida en la creciente separación entre [lo ético y lo legal.](https://longitudsinanchura.com/2022/08/09/los-peligros-de-la-moralidad/)
24. Tu deber es gritar las verdades que se deberían gritar pero solo se susurran.
25. Virtud es cuando los ingresos que deseas mostrar a la agencia Tributaria superan a los que deseas mostrar a tu vecino.
26. El problema con la idea de aprender de los propios errores es que la mayor parte de lo que la gente llama errores no lo son.
27. Para el robusto, un error es información; para el frágil, un error es un error.
28. Ánclate en lo que no ha sucedido en lugar de en lo que ha sucedido.
30. Contra la creencia imperante, éxito no significa estar en la cima de una jerarquía. Significa estar fuera de todas las jerarquías.
31. Si algo parece irracional, y lo ha sido por mucho tiempo, es posible que tengas una definición equivocada de la racionalidad.
32. Lo que cuenta no es lo que la gente dice de ti, sino la energía que gasta para decirlo.


Links de afiliado:
- Comprar [libro de papel.](https://amzn.to/3qaTt86) 
- Comprar [libro electrónico.](https://amzn.to/3cOhIGk)

