<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Introduction to R</title>
  <meta name="description" content="R contents and material for classes. Excel users may be the target." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Introduction to R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="R contents and material for classes. Excel users may be the target." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to R" />
  
  <meta name="twitter:description" content="R contents and material for classes. Excel users may be the target." />
  

<meta name="author" content="Leonardo Hansa" />


<meta name="date" content="2021-04-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  

<link rel="next" href="reading-data-with-readr.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="first-steps.html"><a href="first-steps.html"><i class="fa fa-check"></i><b>1</b> First steps</a>
<ul>
<li class="chapter" data-level="1.1" data-path="first-steps.html"><a href="first-steps.html#programming-in-r"><i class="fa fa-check"></i><b>1.1</b> Programming in R</a></li>
<li class="chapter" data-level="1.2" data-path="first-steps.html"><a href="first-steps.html#r-as-a-calculator"><i class="fa fa-check"></i><b>1.2</b> R as a calculator</a></li>
<li class="chapter" data-level="1.3" data-path="first-steps.html"><a href="first-steps.html#simple-types-of-objects"><i class="fa fa-check"></i><b>1.3</b> Simple types of objects</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="first-steps.html"><a href="first-steps.html#numeric"><i class="fa fa-check"></i><b>1.3.1</b> Numeric</a></li>
<li class="chapter" data-level="1.3.2" data-path="first-steps.html"><a href="first-steps.html#character"><i class="fa fa-check"></i><b>1.3.2</b> Character</a></li>
<li class="chapter" data-level="1.3.3" data-path="first-steps.html"><a href="first-steps.html#logical"><i class="fa fa-check"></i><b>1.3.3</b> Logical</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="first-steps.html"><a href="first-steps.html#sets-of-elements"><i class="fa fa-check"></i><b>1.4</b> Sets of elements</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="first-steps.html"><a href="first-steps.html#vectors"><i class="fa fa-check"></i><b>1.4.1</b> Vectors</a></li>
<li class="chapter" data-level="1.4.2" data-path="first-steps.html"><a href="first-steps.html#matrix"><i class="fa fa-check"></i><b>1.4.2</b> Matrix</a></li>
<li class="chapter" data-level="1.4.3" data-path="first-steps.html"><a href="first-steps.html#data-frames"><i class="fa fa-check"></i><b>1.4.3</b> Data frames</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="first-steps.html"><a href="first-steps.html#extending-r-with-libraries"><i class="fa fa-check"></i><b>1.5</b> Extending R with libraries</a></li>
<li class="chapter" data-level="1.6" data-path="first-steps.html"><a href="first-steps.html#installation"><i class="fa fa-check"></i><b>1.6</b> Installation</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html"><i class="fa fa-check"></i><b>2</b> Reading data with readr</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html#excel"><i class="fa fa-check"></i><b>2.1</b> Excel</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html#about-the-names"><i class="fa fa-check"></i><b>2.1.1</b> About the names</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html#what-is-a-csv-file"><i class="fa fa-check"></i><b>2.2</b> What is a csv file</a></li>
<li class="chapter" data-level="2.3" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html#reading-a-csv"><i class="fa fa-check"></i><b>2.3</b> Reading a csv</a></li>
<li class="chapter" data-level="2.4" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html#reading-other-tabular-data"><i class="fa fa-check"></i><b>2.4</b> Reading other tabular data</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html#another-csv"><i class="fa fa-check"></i><b>2.4.1</b> Another csv</a></li>
<li class="chapter" data-level="2.4.2" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html#tsv"><i class="fa fa-check"></i><b>2.4.2</b> tsv</a></li>
<li class="chapter" data-level="2.4.3" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html#release-your-imagination"><i class="fa fa-check"></i><b>2.4.3</b> Release your imagination</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="reading-data-with-readr.html"><a href="reading-data-with-readr.html#more-things"><i class="fa fa-check"></i><b>2.5</b> More things</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="working-with-tables.html"><a href="working-with-tables.html"><i class="fa fa-check"></i><b>3</b> Working with tables</a>
<ul>
<li class="chapter" data-level="3.1" data-path="working-with-tables.html"><a href="working-with-tables.html#creating-and-selecting-columns"><i class="fa fa-check"></i><b>3.1</b> Creating and selecting columns</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="working-with-tables.html"><a href="working-with-tables.html#mtcars-dataset"><i class="fa fa-check"></i><b>3.1.1</b> mtcars dataset</a></li>
<li class="chapter" data-level="3.1.2" data-path="working-with-tables.html"><a href="working-with-tables.html#invented-dataset"><i class="fa fa-check"></i><b>3.1.2</b> Invented dataset</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="working-with-tables.html"><a href="working-with-tables.html#filtering-rows"><i class="fa fa-check"></i><b>3.2</b> Filtering rows</a></li>
<li class="chapter" data-level="3.3" data-path="working-with-tables.html"><a href="working-with-tables.html#distinct"><i class="fa fa-check"></i><b>3.3</b> Distinct</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="working-with-tables.html"><a href="working-with-tables.html#r-base"><i class="fa fa-check"></i><b>3.3.1</b> R base</a></li>
<li class="chapter" data-level="3.3.2" data-path="working-with-tables.html"><a href="working-with-tables.html#dplyr"><i class="fa fa-check"></i><b>3.3.2</b> dplyr</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="working-with-tables.html"><a href="working-with-tables.html#some-comments-about-na"><i class="fa fa-check"></i><b>3.4</b> Some comments about <code>NA</code></a></li>
<li class="chapter" data-level="3.5" data-path="working-with-tables.html"><a href="working-with-tables.html#row-numbers"><i class="fa fa-check"></i><b>3.5</b> Row numbers</a></li>
<li class="chapter" data-level="3.6" data-path="working-with-tables.html"><a href="working-with-tables.html#exercises"><i class="fa fa-check"></i><b>3.6</b> Exercises</a></li>
<li class="chapter" data-level="3.7" data-path="working-with-tables.html"><a href="working-with-tables.html#summarizing-tables"><i class="fa fa-check"></i><b>3.7</b> Summarizing tables</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="working-with-tables.html"><a href="working-with-tables.html#exercises-1"><i class="fa fa-check"></i><b>3.7.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="working-with-tables.html"><a href="working-with-tables.html#aggregating-the-data"><i class="fa fa-check"></i><b>3.8</b> Aggregating the data</a></li>
<li class="chapter" data-level="3.9" data-path="working-with-tables.html"><a href="working-with-tables.html#a-summary"><i class="fa fa-check"></i><b>3.9</b> A summary</a></li>
<li class="chapter" data-level="3.10" data-path="working-with-tables.html"><a href="working-with-tables.html#dplyr-verbs"><i class="fa fa-check"></i><b>3.10</b> Dplyr verbs</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="working-with-tables.html"><a href="working-with-tables.html#filter-rows-with-filter"><i class="fa fa-check"></i><b>3.10.1</b> Filter rows with filter()</a></li>
<li class="chapter" data-level="3.10.2" data-path="working-with-tables.html"><a href="working-with-tables.html#arrange-rows-with-arrange"><i class="fa fa-check"></i><b>3.10.2</b> Arrange rows with <code>arrange()</code></a></li>
<li class="chapter" data-level="3.10.3" data-path="working-with-tables.html"><a href="working-with-tables.html#select-columns-with-select"><i class="fa fa-check"></i><b>3.10.3</b> Select columns with <code>select()</code></a></li>
<li class="chapter" data-level="3.10.4" data-path="working-with-tables.html"><a href="working-with-tables.html#add-new-columns-with-mutate"><i class="fa fa-check"></i><b>3.10.4</b> Add new columns with <code>mutate()</code></a></li>
<li class="chapter" data-level="3.10.5" data-path="working-with-tables.html"><a href="working-with-tables.html#summarise-values-with-summarise"><i class="fa fa-check"></i><b>3.10.5</b> Summarise values with <code>summarise()</code></a></li>
<li class="chapter" data-level="3.10.6" data-path="working-with-tables.html"><a href="working-with-tables.html#randomly-sample-rows-with-sample_n-and-sample_frac"><i class="fa fa-check"></i><b>3.10.6</b> Randomly sample rows with <code>sample_n()</code> and <code>sample_frac()</code></a></li>
<li class="chapter" data-level="3.10.7" data-path="working-with-tables.html"><a href="working-with-tables.html#commonalities"><i class="fa fa-check"></i><b>3.10.7</b> Commonalities</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="working-with-tables.html"><a href="working-with-tables.html#grouped-operations"><i class="fa fa-check"></i><b>3.11</b> Grouped operations</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>4</b> Data visualization</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-visualization.html"><a href="data-visualization.html#first-steps-into-dataviz"><i class="fa fa-check"></i><b>4.1</b> First steps into dataviz</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="data-visualization.html"><a href="data-visualization.html#ggplot2"><i class="fa fa-check"></i><b>4.1.1</b> ggplot2</a></li>
<li class="chapter" data-level="4.1.2" data-path="data-visualization.html"><a href="data-visualization.html#scatter-plot"><i class="fa fa-check"></i><b>4.1.2</b> Scatter plot</a></li>
<li class="chapter" data-level="4.1.3" data-path="data-visualization.html"><a href="data-visualization.html#columns"><i class="fa fa-check"></i><b>4.1.3</b> Columns</a></li>
<li class="chapter" data-level="4.1.4" data-path="data-visualization.html"><a href="data-visualization.html#lines"><i class="fa fa-check"></i><b>4.1.4</b> Lines</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data-visualization.html"><a href="data-visualization.html#exercises-about-scatter-plots"><i class="fa fa-check"></i><b>4.2</b> Exercises about scatter plots</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="data-visualization.html"><a href="data-visualization.html#exercise-1"><i class="fa fa-check"></i><b>4.2.1</b> Exercise 1</a></li>
<li class="chapter" data-level="4.2.2" data-path="data-visualization.html"><a href="data-visualization.html#exercise-2"><i class="fa fa-check"></i><b>4.2.2</b> Exercise 2</a></li>
<li class="chapter" data-level="4.2.3" data-path="data-visualization.html"><a href="data-visualization.html#exercise-3"><i class="fa fa-check"></i><b>4.2.3</b> Exercise 3</a></li>
<li class="chapter" data-level="4.2.4" data-path="data-visualization.html"><a href="data-visualization.html#exercise-4"><i class="fa fa-check"></i><b>4.2.4</b> Exercise 4</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data-visualization.html"><a href="data-visualization.html#exercises-about-line-plots"><i class="fa fa-check"></i><b>4.3</b> Exercises about line plots</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="data-visualization.html"><a href="data-visualization.html#exercise-1-1"><i class="fa fa-check"></i><b>4.3.1</b> Exercise 1</a></li>
<li class="chapter" data-level="4.3.2" data-path="data-visualization.html"><a href="data-visualization.html#exercise-2-1"><i class="fa fa-check"></i><b>4.3.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="data-visualization.html"><a href="data-visualization.html#columns-and-boxplots"><i class="fa fa-check"></i><b>4.4</b> Columns and boxplots</a></li>
<li class="chapter" data-level="4.5" data-path="data-visualization.html"><a href="data-visualization.html#preparing-the-data"><i class="fa fa-check"></i><b>4.5</b> Preparing the data</a></li>
<li class="chapter" data-level="4.6" data-path="data-visualization.html"><a href="data-visualization.html#bar-plots"><i class="fa fa-check"></i><b>4.6</b> Bar plots</a></li>
<li class="chapter" data-level="4.7" data-path="data-visualization.html"><a href="data-visualization.html#histograms"><i class="fa fa-check"></i><b>4.7</b> Histograms</a></li>
<li class="chapter" data-level="4.8" data-path="data-visualization.html"><a href="data-visualization.html#boxplots"><i class="fa fa-check"></i><b>4.8</b> Boxplots</a></li>
<li class="chapter" data-level="4.9" data-path="data-visualization.html"><a href="data-visualization.html#some-improvements"><i class="fa fa-check"></i><b>4.9</b> Some improvements</a></li>
<li class="chapter" data-level="4.10" data-path="data-visualization.html"><a href="data-visualization.html#mixing-data"><i class="fa fa-check"></i><b>4.10</b> Mixing data</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="data-visualization.html"><a href="data-visualization.html#exercise"><i class="fa fa-check"></i><b>4.10.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="data-visualization.html"><a href="data-visualization.html#facets-the-basics"><i class="fa fa-check"></i><b>4.11</b> Facets: The basics</a></li>
<li class="chapter" data-level="4.12" data-path="data-visualization.html"><a href="data-visualization.html#many-variables-in-just-one-plot"><i class="fa fa-check"></i><b>4.12</b> Many variables in just one plot</a></li>
<li class="chapter" data-level="4.13" data-path="data-visualization.html"><a href="data-visualization.html#something-more"><i class="fa fa-check"></i><b>4.13</b> Something more</a>
<ul>
<li class="chapter" data-level="4.13.1" data-path="data-visualization.html"><a href="data-visualization.html#pivoting-data"><i class="fa fa-check"></i><b>4.13.1</b> Pivoting data</a></li>
<li class="chapter" data-level="4.13.2" data-path="data-visualization.html"><a href="data-visualization.html#basic-scatter-plot"><i class="fa fa-check"></i><b>4.13.2</b> Basic scatter plot</a></li>
<li class="chapter" data-level="4.13.3" data-path="data-visualization.html"><a href="data-visualization.html#facet-rows-accoding-to-vore"><i class="fa fa-check"></i><b>4.13.3</b> Facet rows accoding to vore</a></li>
<li class="chapter" data-level="4.13.4" data-path="data-visualization.html"><a href="data-visualization.html#specify-scale-and-space-arguments-to-free-up-rows"><i class="fa fa-check"></i><b>4.13.4</b> Specify scale and space arguments to free up rows</a></li>
</ul></li>
<li class="chapter" data-level="4.14" data-path="data-visualization.html"><a href="data-visualization.html#united-nations-life-expectancy-data"><i class="fa fa-check"></i><b>4.14</b> United Nations life expectancy data</a></li>
<li class="chapter" data-level="4.15" data-path="data-visualization.html"><a href="data-visualization.html#life-expectancy-of-men-vs.-women-by-country"><i class="fa fa-check"></i><b>4.15</b> Life expectancy of men vs. women by country</a></li>
<li class="chapter" data-level="4.16" data-path="data-visualization.html"><a href="data-visualization.html#visualize-i"><i class="fa fa-check"></i><b>4.16</b> Visualize (I)</a></li>
<li class="chapter" data-level="4.17" data-path="data-visualization.html"><a href="data-visualization.html#reference-lines-i"><i class="fa fa-check"></i><b>4.17</b> Reference lines (I)</a></li>
<li class="chapter" data-level="4.18" data-path="data-visualization.html"><a href="data-visualization.html#plot-titles-and-axis-labels"><i class="fa fa-check"></i><b>4.18</b> Plot titles and axis labels</a></li>
<li class="chapter" data-level="4.19" data-path="data-visualization.html"><a href="data-visualization.html#highlighting-remarkable-countries-i"><i class="fa fa-check"></i><b>4.19</b> Highlighting remarkable countries (I)</a></li>
<li class="chapter" data-level="4.20" data-path="data-visualization.html"><a href="data-visualization.html#gif"><i class="fa fa-check"></i><b>4.20</b> GIF</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="programming-concepts.html"><a href="programming-concepts.html"><i class="fa fa-check"></i><b>5</b> Programming concepts</a>
<ul>
<li class="chapter" data-level="5.1" data-path="programming-concepts.html"><a href="programming-concepts.html#purpose-of-functions"><i class="fa fa-check"></i><b>5.1</b> Purpose of functions</a></li>
<li class="chapter" data-level="5.2" data-path="programming-concepts.html"><a href="programming-concepts.html#the-arguments"><i class="fa fa-check"></i><b>5.2</b> The arguments</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="programming-concepts.html"><a href="programming-concepts.html#order-of-the-arguments"><i class="fa fa-check"></i><b>5.2.1</b> Order of the arguments</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="programming-concepts.html"><a href="programming-concepts.html#the-value"><i class="fa fa-check"></i><b>5.3</b> The value</a></li>
<li class="chapter" data-level="5.4" data-path="programming-concepts.html"><a href="programming-concepts.html#your-own-functions"><i class="fa fa-check"></i><b>5.4</b> Your own functions</a></li>
<li class="chapter" data-level="5.5" data-path="programming-concepts.html"><a href="programming-concepts.html#exercises-2"><i class="fa fa-check"></i><b>5.5</b> Exercises</a></li>
<li class="chapter" data-level="5.6" data-path="programming-concepts.html"><a href="programming-concepts.html#conditions"><i class="fa fa-check"></i><b>5.6</b> Conditions</a></li>
<li class="chapter" data-level="5.7" data-path="programming-concepts.html"><a href="programming-concepts.html#joining-data-frames-with-dplyr"><i class="fa fa-check"></i><b>5.7</b> Joining data frames with dplyr</a></li>
<li class="chapter" data-level="5.8" data-path="programming-concepts.html"><a href="programming-concepts.html#binding-data-frames"><i class="fa fa-check"></i><b>5.8</b> Binding data frames</a></li>
<li class="chapter" data-level="5.9" data-path="programming-concepts.html"><a href="programming-concepts.html#exercises-3"><i class="fa fa-check"></i><b>5.9</b> Exercises</a></li>
<li class="chapter" data-level="5.10" data-path="programming-concepts.html"><a href="programming-concepts.html#applying-the-same-function-to-several-elements-i"><i class="fa fa-check"></i><b>5.10</b> Applying the same function to several elements (I)</a></li>
<li class="chapter" data-level="5.11" data-path="programming-concepts.html"><a href="programming-concepts.html#lists"><i class="fa fa-check"></i><b>5.11</b> Lists</a></li>
<li class="chapter" data-level="5.12" data-path="programming-concepts.html"><a href="programming-concepts.html#applying-the-same-function-to-several-elements-ii"><i class="fa fa-check"></i><b>5.12</b> Applying the same function to several elements (II)</a></li>
<li class="chapter" data-level="5.13" data-path="programming-concepts.html"><a href="programming-concepts.html#exercise-5"><i class="fa fa-check"></i><b>5.13</b> Exercise</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Introduction to R</h1>
<h2 class="subtitle"><em>Maybe especially useful for Excel users</em></h2>
<p class="author"><em>Leonardo Hansa</em></p>
<p class="date"><em>2021-04-04</em></p>
</div>
<div id="first-steps" class="section level1" number="1">
<h1><span class="header-section-number">1</span> First steps</h1>
<p>R is an environment for statistical analysis, including gathering, modelling and visualizing data. We also call R the programming language used on this environment (<a href="http://www.r-project.org/" class="uri">http://www.r-project.org/</a>).</p>
<div id="programming-in-r" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Programming in R</h2>
<p>Why you should use R?</p>
<ul>
<li>Free and open</li>
<li>It includes lots of tools for plots</li>
<li>There is an interface, RStudio, which makes R projects very comfortable</li>
<li>Available on Windows, Mac and Linux</li>
<li>Console, scripts and notebooks available</li>
<li>Updated with state-of-art methodologies</li>
<li><a href="https://www.r-project.org/">Users community</a>.</li>
</ul>
<p>What trouble you will find.</p>
<ul>
<li>It is really difficult become an expert on every aspects of R</li>
<li>Maintenance of codes will be hard if the language is used unproperly</li>
<li>Execution can be very slow if the language is used unproperly</li>
<li>Too much RAM can be needed</li>
</ul>
<p>There are several tools that can be used for programming in R. The most spread one is <a href="https://www.rstudio.com">RStudio</a>. The company behind this software provides users with a very complete free version. They also work on several tools for R but independently from the R project.</p>
<p>Copy and pasting is a great way for developing good scripts. RStudio have written several cheatsheets with key content to getting started with some of the R tools. We may get some help from them. Go and visit their <a href="https://www.rstudio.com/resources/cheatsheets/">website</a>.</p>
</div>
<div id="r-as-a-calculator" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> R as a calculator</h2>
<p>Our first approach to R will be using it as a calculator. Later on, we will begin taking advantage of it as a programming language. The main idea of these first lines is that we can compute both easy and complex calculations using the console of RStudio (some comments about RStudio IDE will be given during the lessons).</p>
<p>We can compute elementary mathematical operations, with common notation.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="first-steps.html#cb1-1"></a><span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span></span>
<span id="cb1-2"><a href="first-steps.html#cb1-2"></a><span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="dv">100</span></span>
<span id="cb1-3"><a href="first-steps.html#cb1-3"></a><span class="dv">20</span> <span class="op">/</span><span class="st"> </span><span class="dv">4</span></span>
<span id="cb1-4"><a href="first-steps.html#cb1-4"></a><span class="dv">20</span> <span class="op">/</span><span class="st"> </span><span class="dv">3</span></span>
<span id="cb1-5"><a href="first-steps.html#cb1-5"></a><span class="dv">2</span> <span class="op">**</span><span class="st"> </span><span class="dv">10</span></span>
<span id="cb1-6"><a href="first-steps.html#cb1-6"></a><span class="dv">2</span> <span class="op">^</span><span class="st"> </span><span class="dv">10</span></span></code></pre></div>
<p>For more complex operations we need <em>functions.</em> Functions (in any programming language) are pieces of code that make some operations. We’ll get into them later on in the course. For now, it is enough knowing that R provide us with a lot of functions to make lots of calculations.</p>
<pre><code>## [1] 120</code></pre>
<pre><code>## [1] 1.224647e-16</code></pre>
<p>Suppose we want to calculate the force that is needed if we want to move an object of 9.5 <span class="math inline">\(kg\)</span> with an accelaration of 4.7 <span class="math inline">\(m/{s^2}\)</span>. Newton’s second law may help: <span class="math inline">\(F = m\cdot a\)</span>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="first-steps.html#cb4-1"></a><span class="fl">9.5</span> <span class="op">*</span><span class="st"> </span><span class="fl">4.7</span></span></code></pre></div>
<pre><code>## [1] 44.65</code></pre>
<p>Yeah! Cool, we did it! We now know that 44.65 <span class="math inline">\(N\)</span> are needed to move the object. The thing is that we will need to repeat the operation every time we desire to see the result. Avoiding that repetition can be achieved giving a name to that operation. <code>newton</code> seems a nice selection. We do this by using the <code>&lt;-</code> symbol.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="first-steps.html#cb6-1"></a>newton &lt;-<span class="st"> </span><span class="fl">9.5</span> <span class="op">*</span><span class="st"> </span><span class="fl">4.7</span></span>
<span id="cb6-2"><a href="first-steps.html#cb6-2"></a>newton</span></code></pre></div>
<pre><code>## [1] 44.65</code></pre>
<p>Now, every time we write <code>newton</code> on the console we will get that result. In fact, on the upper right side of our RStudio windows we will see that something called <code>newton</code> has appeared, with a value of 44.65.</p>
<p>This idea can also be applied to the mass and the acceleration. We should define <em>something</em> with the mass value and another <em>something</em> with the acceleration value. In the future we will understand why this is so important.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="first-steps.html#cb8-1"></a>acc &lt;-<span class="st"> </span><span class="fl">4.7</span></span>
<span id="cb8-2"><a href="first-steps.html#cb8-2"></a>mass &lt;-<span class="st"> </span><span class="fl">9.5</span></span>
<span id="cb8-3"><a href="first-steps.html#cb8-3"></a>newton &lt;-<span class="st"> </span>mass <span class="op">*</span><span class="st"> </span>acc</span>
<span id="cb8-4"><a href="first-steps.html#cb8-4"></a>newton</span></code></pre></div>
<pre><code>## [1] 44.65</code></pre>
<p><strong>Exercises.</strong></p>
<ul>
<li><p>Change the values of <code>acc</code> and <code>mass</code> (make sure on the upper right corner of RStudio that you have actually changed them). Write on the console <code>newton</code>. Try to understand what is necessary for successfully getting that change.</p></li>
<li><p>What happens if you use <code>=</code> instead of <code>&lt;-</code>? We will get into this by the end of the course. The idea right now is that the former is the one chosen as a good-practice standard.</p></li>
<li><p>You have defined <code>acc</code>. Type <code>ACC</code> and see what happens when you try to work with it.</p></li>
</ul>
</div>
<div id="simple-types-of-objects" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Simple types of objects</h2>
<p>When programming (not only with R but in general) we will use elements such as <code>3</code>, <code>-2.5</code>, <code>"cool_element"</code>, <code>a_function_with_nice_properties()</code>… They are different in many ways but they all are objects for R. R understands that both <code>3</code> and <code>"cool_element"</code> are <em>things</em> with different properties. For instance, you can add <code>3</code> and <code>2</code> but can’t <code>3</code> and <code>"cool_element"</code>. These properties the <em>thing</em> (or object) has are what make it belong to a class or other. <code>3</code> in the real life is a number and <code>"cool_element"</code> is text. R needs to know that so that it will work differently with both of them. To do this, <code>3</code> belongs to the class <code>numeric</code> and <code>"cool_element"</code> to the class <code>character</code> (commonly called string in other languages). We’ll get into details in the next lines.</p>
<p></br></p>
<p>When we want to know what type of object we’re working with we’ll use the function <code>class()</code>. Let’s get into details.</p>
<p><strong>Remark.</strong> When the documentation about a funcion is needed, is easily accesible via <code>? name_of_the_function</code>, e.g., <code>? class</code>. The focus of RStudio will move to the tab <em>Help</em>, on the lower left side of the window, by default.</p>
<div id="numeric" class="section level3" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Numeric</h3>
<p>We have already seen some examples with numbers in R.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="first-steps.html#cb10-1"></a><span class="dv">1</span></span>
<span id="cb10-2"><a href="first-steps.html#cb10-2"></a><span class="fl">2.3</span></span>
<span id="cb10-3"><a href="first-steps.html#cb10-3"></a><span class="fl">-1003.65</span></span>
<span id="cb10-4"><a href="first-steps.html#cb10-4"></a>pi</span></code></pre></div>
<div id="integer" class="section level4" number="1.3.1.1">
<h4><span class="header-section-number">1.3.1.1</span> Integer</h4>
<p>Remember from high school the differences between real and integer numbers. 1, 1024, -53 are integers, but 0.5, -1.333 or <span class="math inline">\(\pi\)</span> aren’t. In R there exists a way of indicating such a difference and is important when dealing with large sets of data. The reason behind this is that R needs less information about an integer than about a real number. We will not get into the technical details in this course.</p>
<p>If we define a variable <code>my_number</code> as <code>my_number &lt;- 10</code>, R will not understand the variable as integer, but a real number, therefore, numeric.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="first-steps.html#cb11-1"></a>my_number &lt;-<span class="st"> </span><span class="dv">10</span></span>
<span id="cb11-2"><a href="first-steps.html#cb11-2"></a><span class="kw">class</span>(my_number)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>For letting R know this variable should be define as integer, we use <code>L</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="first-steps.html#cb13-1"></a>my_number &lt;-<span class="st"> </span>10L</span>
<span id="cb13-2"><a href="first-steps.html#cb13-2"></a><span class="kw">class</span>(my_number)</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>Numerical operations apply similarly to integer variables.</p>
</div>
</div>
<div id="character" class="section level3" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Character</h3>
<p>Even though statistics deals always with numbers, saving text data is mandatory to understand what information we have. For example, we may have a table with population data of several cities, but we need to have those cities’ names to relate each piece of population data with the city. Thus, we need a way to tell R that a text is a text, so that it will understand it doesn’t have to work with it as if it were a number.</p>
<p>The way of doing this is <code>""</code>. Some examples:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="first-steps.html#cb15-1"></a>city &lt;-<span class="st"> &quot;Madrid&quot;</span></span>
<span id="cb15-2"><a href="first-steps.html#cb15-2"></a>capital_letters &lt;-<span class="st"> &quot;NEW YORK&quot;</span></span>
<span id="cb15-3"><a href="first-steps.html#cb15-3"></a>a_number &lt;-<span class="st"> &quot;10&quot;</span></span>
<span id="cb15-4"><a href="first-steps.html#cb15-4"></a>strange_characters &lt;-<span class="st"> &quot;@!-/&quot;</span></span>
<span id="cb15-5"><a href="first-steps.html#cb15-5"></a>all_together &lt;-<span class="st"> &quot;¿Cuál es la capital de España?&quot;</span></span></code></pre></div>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="first-steps.html#cb16-1"></a><span class="kw">class</span>(city)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="first-steps.html#cb18-1"></a><span class="kw">class</span>(all_together)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>We can also operate with character (or string) objects, generally with functions. We may see some examples in other sections but it is not a main goal of the course.</p>
</div>
<div id="logical" class="section level3" number="1.3.3">
<h3><span class="header-section-number">1.3.3</span> Logical</h3>
<p>When programming, you will need to tell the computer to do something taking into account a condition. For example, creating a new folder if it doesn’t exists yet. Thus, R must know whether something is true or false. For this, we have the reserved words <code>TRUE</code> and <code>FALSE</code> (capital letters).</p>
<p>This is crucial when developing your own processes and functions but for now it’ll be enough getting the general idea.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="first-steps.html#cb20-1"></a>saying_yes &lt;-<span class="st"> </span><span class="ot">TRUE</span></span>
<span id="cb20-2"><a href="first-steps.html#cb20-2"></a><span class="kw">class</span>(saying_yes)</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<p><strong>Remark.</strong> Generally, the logical type is called boolean in other programming languages and it is easy finding documentation refering to this word, even about R.</p>
<p><strong>Another remark.</strong> What the programming language hide behind a logical value is a number. <code>TRUE</code> equals 1 and <code>FALSE</code> equals 0.</p>
<p>We have seen some examples of operations with numbers but we can also compare them in the usual way.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="first-steps.html#cb22-1"></a>pi <span class="op">&gt;</span><span class="st"> </span><span class="dv">3</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="first-steps.html#cb24-1"></a><span class="kw">log10</span>(<span class="dv">100</span>) <span class="op">==</span><span class="st"> </span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="first-steps.html#cb26-1"></a><span class="dv">-3</span> <span class="op">&lt;=</span><span class="st"> </span><span class="dv">-4</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="first-steps.html#cb28-1"></a><span class="ot">TRUE</span> <span class="op">==</span><span class="st"> </span><span class="dv">1</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="first-steps.html#cb30-1"></a><span class="ot">FALSE</span> <span class="op">==</span><span class="st"> </span><span class="dv">0</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="first-steps.html#cb32-1"></a><span class="ot">TRUE</span> <span class="op">==</span><span class="st"> </span><span class="dv">3</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>We can assign these comparisons to variables.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="first-steps.html#cb34-1"></a>comparison1 &lt;-<span class="st"> </span>pi <span class="op">&gt;</span><span class="st"> </span><span class="dv">3</span></span>
<span id="cb34-2"><a href="first-steps.html#cb34-2"></a>comparison2 &lt;-<span class="st"> </span><span class="kw">log10</span>(<span class="dv">100</span>) <span class="op">==</span><span class="st"> </span><span class="dv">2</span></span>
<span id="cb34-3"><a href="first-steps.html#cb34-3"></a>comparison3 &lt;-<span class="st"> </span><span class="dv">-3</span> <span class="op">&lt;=</span><span class="st"> </span><span class="dv">-4</span></span>
<span id="cb34-4"><a href="first-steps.html#cb34-4"></a></span>
<span id="cb34-5"><a href="first-steps.html#cb34-5"></a><span class="kw">class</span>(comparison1)</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="first-steps.html#cb36-1"></a><span class="kw">class</span>(comparison2)</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="first-steps.html#cb38-1"></a><span class="kw">class</span>(comparison3)</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<p>We will see a practical example of this when introducing the tables (data frames).</p>
</div>
</div>
<div id="sets-of-elements" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Sets of elements</h2>
<div id="vectors" class="section level3" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> Vectors</h3>
<p>In statistics we usually work with sets of data, i.e., several numbers. Imagine we have data about the height of several people and want to calculate the average height. We can pass this numbers to the R function <code>mean()</code>, which will return the desire result.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="first-steps.html#cb40-1"></a><span class="kw">mean</span>(<span class="fl">1.75</span>, <span class="fl">1.69</span>, <span class="fl">1.81</span>, <span class="fl">1.65</span>, <span class="fl">2.01</span>, <span class="fl">1.73</span>, <span class="fl">1.90</span>, <span class="fl">1.62</span>)</span></code></pre></div>
<pre><code>## [1] 1.75</code></pre>
<p>If we want to use that set again for another calculations (e.g., standard deviation with <code>sd()</code>), we need to define a new variable in R with those numbers. Writing them in the same way we have just done would return an error.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="first-steps.html#cb42-1"></a>my_set &lt;-<span class="st"> </span><span class="fl">1.75</span>, <span class="fl">1.69</span>, <span class="fl">1.81</span>, <span class="fl">1.65</span>, <span class="fl">2.01</span>, <span class="fl">1.73</span>, <span class="fl">1.90</span>, <span class="fl">1.62</span></span>
<span id="cb42-2"><a href="first-steps.html#cb42-2"></a><span class="co"># Error: unexpected &#39;,&#39; in &quot;my_set &lt;- 1.75,&quot;</span></span></code></pre></div>
<p>For managing R to understand those numbers should be saved in the same variable all together, with need the <code>c()</code> function.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="first-steps.html#cb43-1"></a>my_set &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">1.75</span>, <span class="fl">1.69</span>, <span class="fl">1.81</span>, <span class="fl">1.65</span>, <span class="fl">2.01</span>, <span class="fl">1.73</span>, <span class="fl">1.90</span>, <span class="fl">1.62</span>)</span>
<span id="cb43-2"><a href="first-steps.html#cb43-2"></a>my_set</span></code></pre></div>
<pre><code>## [1] 1.75 1.69 1.81 1.65 2.01 1.73 1.90 1.62</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="first-steps.html#cb45-1"></a><span class="kw">mean</span>(my_set)</span></code></pre></div>
<pre><code>## [1] 1.77</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="first-steps.html#cb47-1"></a><span class="kw">sd</span>(my_set)</span></code></pre></div>
<pre><code>## [1] 0.1316923</code></pre>
<p>The avarage height is 1.77 meters and the standard deviation is 13 centimeters.</p>
<p></br></p>
<p>These sets of elements are called vectors. A vector in R is a set of objects of the <strong>same</strong> type. However, if ask R about the class of a vector, it will say the class is the one of the elements.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="first-steps.html#cb49-1"></a><span class="kw">class</span>(<span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>))</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="first-steps.html#cb51-1"></a><span class="kw">class</span>(<span class="kw">c</span>(<span class="st">&quot;hi there!&quot;</span>, <span class="st">&quot;I don&#39;t really understand this R stuff&quot;</span>, <span class="st">&quot;abc10&quot;</span>))</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="first-steps.html#cb53-1"></a><span class="kw">class</span>(<span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>))</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<p>The length of the vector is the number of elements it contains and can be consuted with the <code>length()</code> function. We can extract individual elements from a vector or subsets of it with squared brackets (<code>[]</code>) and the desired indexes. <strong>The index of the first element of the vector is 1.</strong> For several programming languages, such as Python the first index is 0.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="first-steps.html#cb55-1"></a>my_set[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 1.69</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="first-steps.html#cb57-1"></a>my_desired_index &lt;-<span class="st"> </span><span class="dv">3</span></span>
<span id="cb57-2"><a href="first-steps.html#cb57-2"></a>my_set[my_desired_index]</span></code></pre></div>
<pre><code>## [1] 1.81</code></pre>
<p>Be careful with the notation when mixing vector and functions.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="first-steps.html#cb59-1"></a>my_set[<span class="kw">length</span>(my_set)]</span></code></pre></div>
<pre><code>## [1] 1.62</code></pre>
<p>There is no element in the vector whose index is 0.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="first-steps.html#cb61-1"></a>my_set[<span class="dv">0</span>]</span></code></pre></div>
<pre><code>## numeric(0)</code></pre>
<p>For subsetting instead of extracting indivual elements, we need to provided the <code>[]</code> with another vector, whose numbers will be the indexes of the elements we want.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="first-steps.html#cb63-1"></a>my_indexes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>)</span>
<span id="cb63-2"><a href="first-steps.html#cb63-2"></a>my_set[my_indexes]</span></code></pre></div>
<pre><code>## [1] 1.69 1.65 1.73</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="first-steps.html#cb65-1"></a>my_set[<span class="op">-</span>my_indexes] <span class="co">## all except my_indexes</span></span></code></pre></div>
<pre><code>## [1] 1.75 1.81 2.01 1.90 1.62</code></pre>
<p>For simplyfing, there is no need on writing <code>c(1, 2, 3, 4, 5)</code>. You can use the sequence notation <code>1:5</code>.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="first-steps.html#cb67-1"></a>a &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">5</span></span>
<span id="cb67-2"><a href="first-steps.html#cb67-2"></a>b &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="cb67-3"><a href="first-steps.html#cb67-3"></a></span>
<span id="cb67-4"><a href="first-steps.html#cb67-4"></a>a <span class="op">==</span><span class="st"> </span>b <span class="co">## element by element</span></span></code></pre></div>
<pre><code>## [1] TRUE TRUE TRUE TRUE TRUE</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="first-steps.html#cb69-1"></a>a</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5</code></pre>
<p><strong>Exercise.</strong> What happens when you define a variable with the name <code>c</code>? Bear in mind that <code>c()</code> is a function in R. <em>Spoiler alert.</em> Not much: you just need to be careful and remember you have two different things with the same name, but there wil be no ambiguity since the uses of one of them are different form the other’s.</p>
<p>You can also use this <code>:</code> notation for indexes, as well as logical vectors and integers variables.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="first-steps.html#cb71-1"></a>my_set[4L]</span></code></pre></div>
<pre><code>## [1] 1.65</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="first-steps.html#cb73-1"></a>logical_vector &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>)</span>
<span id="cb73-2"><a href="first-steps.html#cb73-2"></a>my_set[logical_vector]</span></code></pre></div>
<pre><code>## [1] 1.75 1.81 2.01 1.90</code></pre>
<p>Notice that, in the logical indexes case, the length of the index vector and the main vector are the same. This doesn’t have to be like this always, since R knows how to recycle information, though it may be counterintuitive is some ocasions.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="first-steps.html#cb75-1"></a>my_set[<span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>)]</span></code></pre></div>
<pre><code>## [1] 1.75 1.81 2.01 1.90</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="first-steps.html#cb77-1"></a>my_set[<span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>)]</span></code></pre></div>
<pre><code>## [1] 1.75 1.81 1.65 1.73 1.90</code></pre>
</div>
<div id="matrix" class="section level3" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Matrix</h3>
<p>You may have studied matrixes back in high school but for us we will understand them as tables with elements, distributed along rows and columns. As well as we saw with vectors, the elements of a matrix must belong all to the same class.</p>
<p>Vectors were defined via <code>c()</code> but there is no way of indicating a second dimension to this function, so that we can have rows and columns. For achieving this, we use <code>matrix()</code>.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="first-steps.html#cb79-1"></a>my_matrix &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">9</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">-1</span>, <span class="dv">-6</span>, <span class="dv">8</span>, <span class="dv">100</span>, <span class="dv">200</span>, <span class="dv">300</span>), <span class="dt">nrow =</span> <span class="dv">3</span>)</span>
<span id="cb79-2"><a href="first-steps.html#cb79-2"></a>my_matrix</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]   10    1   -1  100
## [2,]   12    5   -6  200
## [3,]    9    7    8  300</code></pre>
<p>There are several considerations that must be taken into account when defining matrixes but we won’t get into them in this course since we will focus on data frames. We’ll just mention a couple of thigs related with working already defined matrixes.</p>
<p>A vector has one only dimension and the number of elements is its length. For matrixes, there is no length concept. Instead, we work with rows and columns.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="first-steps.html#cb81-1"></a><span class="kw">nrow</span>(my_matrix)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="first-steps.html#cb83-1"></a><span class="kw">ncol</span>(my_matrix)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>We have tow dimensions, therefore we need to specify two indexes when extracting elements.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="first-steps.html#cb85-1"></a>desired_row &lt;-<span class="st"> </span><span class="dv">2</span></span>
<span id="cb85-2"><a href="first-steps.html#cb85-2"></a>desired_column &lt;-<span class="st"> </span><span class="dv">4</span></span>
<span id="cb85-3"><a href="first-steps.html#cb85-3"></a></span>
<span id="cb85-4"><a href="first-steps.html#cb85-4"></a>my_matrix[<span class="dv">2</span>, <span class="dv">4</span>]</span></code></pre></div>
<pre><code>## [1] 200</code></pre>
<p>Of course, vectors can also be used as indexes for submatrixes.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="first-steps.html#cb87-1"></a>my_matrix[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>, <span class="dv">3</span><span class="op">:</span><span class="dv">4</span>]</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   -1  100
## [2,]   -6  200</code></pre>
</div>
<div id="data-frames" class="section level3" number="1.4.3">
<h3><span class="header-section-number">1.4.3</span> Data frames</h3>
<p>In statistics, a popular format for keeping data are tables. In R, the main type of tables is called data frame. A data frame is a table, as well as matrixes, but its elements don’t have to be all of the same type. The first column can contain integers, the second, characters, the third, numbers, the fourth, logicals, and so on.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="first-steps.html#cb89-1"></a>my_data_frame &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</span>
<span id="cb89-2"><a href="first-steps.html#cb89-2"></a>  <span class="dt">col1 =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, </span>
<span id="cb89-3"><a href="first-steps.html#cb89-3"></a>  <span class="dt">col2 =</span> <span class="kw">c</span>(<span class="st">&quot;Category 1&quot;</span>, <span class="st">&quot;Category 2&quot;</span>, <span class="st">&quot;Category 3&quot;</span>, <span class="st">&quot;Category 4&quot;</span>), </span>
<span id="cb89-4"><a href="first-steps.html#cb89-4"></a>  <span class="dt">col3 =</span> <span class="kw">c</span>(<span class="fl">3.4</span>, <span class="fl">-2.5</span>, <span class="fl">10.1</span>, <span class="fl">-0.05</span>), </span>
<span id="cb89-5"><a href="first-steps.html#cb89-5"></a>  <span class="dt">col4 =</span> <span class="kw">c</span>(T, F, F, T)</span>
<span id="cb89-6"><a href="first-steps.html#cb89-6"></a>)</span>
<span id="cb89-7"><a href="first-steps.html#cb89-7"></a></span>
<span id="cb89-8"><a href="first-steps.html#cb89-8"></a>my_data_frame</span></code></pre></div>
<pre><code>##   col1       col2  col3  col4
## 1    1 Category 1  3.40  TRUE
## 2    2 Category 2 -2.50 FALSE
## 3    3 Category 3 10.10 FALSE
## 4    4 Category 4 -0.05  TRUE</code></pre>
<p><strong>Exercises.</strong></p>
<ul>
<li>Check the type of each column for the data frame you’ve just created. Remember you need the function <code>class()</code> to do it.</li>
<li>Is there anything strange with the second column? What were you expecting? Ask your teach about this and feel free to read <code>? factor</code> but don’t worry about it for now. We’ll get into that later.</li>
</ul>
<p></br></p>
<p>Data frames have some things in common with matrixes. They are both tables, therefore the same sintax can be used to get their elements:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="first-steps.html#cb91-1"></a>my_data_frame[<span class="dv">1</span>, <span class="dv">2</span>] <span class="co"># first row, second column </span></span></code></pre></div>
<pre><code>## [1] &quot;Category 1&quot;</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="first-steps.html#cb93-1"></a>my_data_frame[<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>, <span class="dv">2</span>] <span class="co"># second to fourth rows, second column </span></span></code></pre></div>
<pre><code>## [1] &quot;Category 2&quot; &quot;Category 3&quot; &quot;Category 4&quot;</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="first-steps.html#cb95-1"></a>my_data_frame[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dv">-4</span>] <span class="co"># first to third rows (included), all except fourth column</span></span></code></pre></div>
<pre><code>##   col1       col2 col3
## 1    1 Category 1  3.4
## 2    2 Category 2 -2.5
## 3    3 Category 3 10.1</code></pre>
<p><strong>Exercise.</strong> What are the types of objects returned with those executions.</p>
<p>As you may have realized, this is a bit messy for beginning working with R. We have mentioned it because it is important to know that this exist, but we will not work with data frames as matrix, but we’ll use the proper tools for data frames that R provides.</p>
<p>First of all, we need to understand how to extract one column in the form of a vector.</p>
<div id="and" class="section level4" number="1.4.3.1">
<h4><span class="header-section-number">1.4.3.1</span> <code>$</code> and <code>[[</code></h4>
<p>You may have noticed that we defined our dataframe with named columns: col1, col2 and so on (it is worth mentioning that this names can be whatever you desire, following some rules we’ll not describe now). This is very convenient since it makes easy getting the elements from each column:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="first-steps.html#cb97-1"></a>my_data_frame<span class="op">$</span>col1</span></code></pre></div>
<pre><code>## [1] 1 2 3 4</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="first-steps.html#cb99-1"></a>my_data_frame[[<span class="st">&quot;col1&quot;</span>]]</span></code></pre></div>
<pre><code>## [1] 1 2 3 4</code></pre>
<ul>
<li><code>$</code> has the advantage of autocompletion (with Tab).</li>
<li><code>[[</code> has the advantage of parametrizing via characters, something very useful when dealing with functions, mainly by the end of the course.</li>
</ul>
<p>There are several ways of verifying those vector are equal. We choose this one:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="first-steps.html#cb101-1"></a>dollar_sintax &lt;-<span class="st"> </span>my_data_frame<span class="op">$</span>col1</span>
<span id="cb101-2"><a href="first-steps.html#cb101-2"></a>double_bracket_sintax &lt;-<span class="st"> </span>my_data_frame[[<span class="st">&quot;col1&quot;</span>]]</span>
<span id="cb101-3"><a href="first-steps.html#cb101-3"></a></span>
<span id="cb101-4"><a href="first-steps.html#cb101-4"></a><span class="kw">all</span>(dollar_sintax <span class="op">==</span><span class="st"> </span>double_bracket_sintax)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>we could have done it at a glance but if you have a one million column data frame, this way’s better ;)</p>
<p><strong>Remark.</strong> Notice we typed double squared bracket (<code>[[</code>), not single (<code>[</code>). The character notation can also be used in the second case but differently and there are more cases to be considered. For simplicity’s sake, we won’t get into that.</p>
<p></br></p>
<p>We don’t know yet how to read data from files (patience, my dear reader) but R makes comfortable using some preloaded datasets as examples. A classical one is <em>iris</em>, a dataset with a some of flowers of three species and some info about them. We will use as a example for a while.</p>
<p>First we should have an idea about the general structure of the data frame. We can type <code>iris</code> on the console and see the data but it is not very clarifying, since there are too many data and don’t fit tidily inside the tab.</p>
<p>A common function for a first approach is <code>head()</code>.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="first-steps.html#cb103-1"></a><span class="kw">head</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<p>Cool. <code>head()</code> shows by default the first six rows of the data frame used as input (be careful if you have too many columns). The analogous is <code>tail()</code>, which shows the last six rows. This number is a parameter of the function and can be redefined.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="first-steps.html#cb105-1"></a><span class="kw">tail</span>(iris, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 141          6.7         3.1          5.6         2.4 virginica
## 142          6.9         3.1          5.1         2.3 virginica
## 143          5.8         2.7          5.1         1.9 virginica
## 144          6.8         3.2          5.9         2.3 virginica
## 145          6.7         3.3          5.7         2.5 virginica
## 146          6.7         3.0          5.2         2.3 virginica
## 147          6.3         2.5          5.0         1.9 virginica
## 148          6.5         3.0          5.2         2.0 virginica
## 149          6.2         3.4          5.4         2.3 virginica
## 150          5.9         3.0          5.1         1.8 virginica</code></pre>
<p>For checking the number of rows and columns of the data frame (these ones also work with matrixes):</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="first-steps.html#cb107-1"></a><span class="kw">nrow</span>(iris)</span></code></pre></div>
<pre><code>## [1] 150</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="first-steps.html#cb109-1"></a><span class="kw">ncol</span>(iris)</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="first-steps.html#cb111-1"></a><span class="kw">dim</span>(iris)</span></code></pre></div>
<pre><code>## [1] 150   5</code></pre>
<p>We have easily verified there are 150 rows and 5 columns. If we want to know what columns there are, we can get their names with <code>names()</code>:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="first-steps.html#cb113-1"></a><span class="kw">names</span>(iris)</span></code></pre></div>
<pre><code>## [1] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot;  &quot;Petal.Length&quot; &quot;Petal.Width&quot;  &quot;Species&quot;</code></pre>
<p>We have info about the sepal, the petal and the species each flower belongs to. We could have also used <code>colnames()</code> for this. Bear in mind that this one would also work with matrixes but the former wouldn’t.</p>
<p>We’ll come back later to have a look at the structure of a data frame with new tools. For now, let’s go on with the <code>$</code> notation.</p>
<p><code>iris</code> is a data frame.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="first-steps.html#cb115-1"></a><span class="kw">class</span>(iris)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>But its columns, from an independent point of view, are vectors. Therefore, their classes are the ones of their elements.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="first-steps.html#cb117-1"></a><span class="kw">class</span>(iris<span class="op">$</span>Sepal.Length)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="first-steps.html#cb119-1"></a><span class="kw">class</span>(iris<span class="op">$</span>Sepal.Width)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="first-steps.html#cb121-1"></a><span class="kw">class</span>(iris<span class="op">$</span>Petal.Length)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="first-steps.html#cb123-1"></a><span class="kw">class</span>(iris<span class="op">$</span>Petal.Width)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="first-steps.html#cb125-1"></a><span class="kw">class</span>(iris<span class="op">$</span>Species)</span></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>We have some numbers and characters (again, don’t worry about the <em>factor</em> thing yet. We’ll come to that). A typical function to get a general idea of the distributions of the columns is <code>summary()</code>.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="first-steps.html#cb127-1"></a><span class="kw">summary</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
<p>Let’s count the number of flowers with a longer sepal than the mean (5.8, according to the summary).</p>
<ul>
<li>First we need to know, for each row, whether the sepal length is greater than 5.8: <code>iris$Sepal.Length &gt; 5.8</code>.</li>
<li>That piece of code will return a vector of 150 <code>TRUE</code> or <code>FALSE</code> values, indicating what we want to know.</li>
<li>Now we need to count how many trues there are. But remember that <code>TRUE == 1</code>, so a good way to counting is adding all the <code>TRUE</code> cases, with <code>sum()</code>.</li>
</ul>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="first-steps.html#cb129-1"></a><span class="kw">sum</span>(iris<span class="op">$</span>Sepal.Length <span class="op">&gt;</span><span class="st"> </span><span class="fl">5.8</span>)</span></code></pre></div>
<pre><code>## [1] 70</code></pre>
<p>There is no need in typing the mean manually. You can use the function <code>mean()</code> instead.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="first-steps.html#cb131-1"></a>my_average &lt;-<span class="st"> </span><span class="kw">mean</span>(iris<span class="op">$</span>Sepal.Length)</span>
<span id="cb131-2"><a href="first-steps.html#cb131-2"></a><span class="kw">sum</span>(iris<span class="op">$</span>Sepal.Length <span class="op">&gt;</span><span class="st"> </span>my_average)</span></code></pre></div>
<pre><code>## [1] 70</code></pre>
<p>This is an example of comparing every row with the same number. But you can use different values for each row. For example, let’s count the number of flowers whose sepal is longer than its petal.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="first-steps.html#cb133-1"></a><span class="kw">sum</span>(iris<span class="op">$</span>Sepal.Length <span class="op">&gt;</span><span class="st"> </span>iris<span class="op">$</span>Petal.Length)</span></code></pre></div>
<pre><code>## [1] 150</code></pre>
<p>All of them. Naïve example.</p>
<p>We can also use these logical vectors to extract subvectors with information. For instance, let’s print the sepal length of the flowers whose petal width is above the median:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="first-steps.html#cb135-1"></a>my_index &lt;-<span class="st"> </span>iris<span class="op">$</span>Petal.Width <span class="op">&gt;</span><span class="st"> </span><span class="kw">median</span>(iris<span class="op">$</span>Petal.Width) <span class="co"># is above the median</span></span>
<span id="cb135-2"><a href="first-steps.html#cb135-2"></a></span>
<span id="cb135-3"><a href="first-steps.html#cb135-3"></a><span class="kw">head</span>(my_index) <span class="co"># these are logical values indicating whether the flower corresponds with the filter</span></span></code></pre></div>
<pre><code>## [1] FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="first-steps.html#cb137-1"></a>iris<span class="op">$</span>Sepal.Length[my_index] </span></code></pre></div>
<pre><code>##  [1] 7.0 6.4 6.9 6.5 6.3 5.2 5.9 6.1 6.7 5.6 6.2 5.9 6.3 6.6 6.8 6.7 6.0 6.0 5.4
## [20] 6.0 6.7 6.1 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4
## [39] 6.5 7.7 7.7 6.0 6.9 5.6 7.7 6.3 6.7 7.2 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1
## [58] 7.7 6.3 6.4 6.0 6.9 6.7 6.9 5.8 6.8 6.7 6.7 6.3 6.5 6.2 5.9</code></pre>
<p>Now we have a subvector of the sepal length. Let’s count the number of flowers with this caracteristic. This will be the number of elements in the vector, what we can calculate with <code>length()</code>.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="first-steps.html#cb139-1"></a><span class="kw">length</span>(iris<span class="op">$</span>Sepal.Length[my_index] )</span></code></pre></div>
<pre><code>## [1] 72</code></pre>
<p>There are 72 flowers whose petal width is above the median.</p>
<p><strong>Exercises.</strong></p>
<ul>
<li>Count the number of flowers with Petal.Length higher than 5.1</li>
</ul>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="first-steps.html#cb141-1"></a><span class="kw">sum</span>(iris<span class="op">$</span>Petal.Length <span class="op">&gt;</span><span class="st"> </span><span class="fl">5.1</span>)</span></code></pre></div>
<pre><code>## [1] 34</code></pre>
<ul>
<li>Check which species have flowers with sepal width higher than 3.5 and lower than 4. <em>Hint.</em> <code>&amp;</code> will be needed when more than one condition is needed. Besides, for simplifying the result you may need <code>unique()</code>. Use <code>?</code> for details.</li>
</ul>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="first-steps.html#cb143-1"></a><span class="kw">unique</span>(iris<span class="op">$</span>Species[iris<span class="op">$</span>Sepal.Width <span class="op">&gt;</span><span class="st"> </span><span class="fl">3.5</span> <span class="op">&amp;</span><span class="st"> </span>iris<span class="op">$</span>Sepal.Width <span class="op">&lt;</span><span class="st"> </span><span class="dv">4</span>])</span></code></pre></div>
<pre><code>## [1] setosa    virginica
## Levels: setosa versicolor virginica</code></pre>
<ul>
<li>How many flowers of each species are there? <em>Hint.</em> Function <code>table()</code> may be useful.</li>
</ul>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="first-steps.html#cb145-1"></a><span class="kw">table</span>(iris<span class="op">$</span>Species)</span></code></pre></div>
<pre><code>## 
##     setosa versicolor  virginica 
##         50         50         50</code></pre>
<ul>
<li>Calculate the sepal width average of the flowers whose sepal width is below average.</li>
</ul>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="first-steps.html#cb147-1"></a><span class="kw">mean</span>(iris<span class="op">$</span>Sepal.Length[iris<span class="op">$</span>Sepal.Width <span class="op">&lt;</span><span class="st"> </span><span class="kw">mean</span>(iris<span class="op">$</span>Sepal.Width)])</span></code></pre></div>
<pre><code>## [1] 5.972289</code></pre>
<ul>
<li>Calculate the median of the petal width for each species separetely.</li>
</ul>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="first-steps.html#cb149-1"></a><span class="kw">print</span>(<span class="st">&quot;Setosa:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Setosa:&quot;</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="first-steps.html#cb151-1"></a><span class="kw">median</span>(iris<span class="op">$</span>Petal.Width[iris<span class="op">$</span>Species <span class="op">==</span><span class="st"> &quot;setosa&quot;</span>])</span></code></pre></div>
<pre><code>## [1] 0.2</code></pre>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="first-steps.html#cb153-1"></a><span class="kw">print</span>(<span class="st">&quot;Versicolor:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Versicolor:&quot;</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="first-steps.html#cb155-1"></a><span class="kw">median</span>(iris<span class="op">$</span>Petal.Width[iris<span class="op">$</span>Species <span class="op">==</span><span class="st"> &quot;versicolor&quot;</span>])</span></code></pre></div>
<pre><code>## [1] 1.3</code></pre>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="first-steps.html#cb157-1"></a><span class="kw">print</span>(<span class="st">&quot;Virginica:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Virginica:&quot;</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="first-steps.html#cb159-1"></a><span class="kw">median</span>(iris<span class="op">$</span>Petal.Width[iris<span class="op">$</span>Species <span class="op">==</span><span class="st"> &quot;virginica&quot;</span>])</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<ul>
<li>Calculate the minimum and maximum petal length for every versicolor flower. Then count how many setosa and virginica flowers there are with the petal length between those values.</li>
</ul>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="first-steps.html#cb161-1"></a><span class="kw">print</span>(<span class="st">&quot;Min:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Min:&quot;</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="first-steps.html#cb163-1"></a>minimo_valor &lt;-<span class="st"> </span><span class="kw">min</span>(iris<span class="op">$</span>Petal.Length[iris<span class="op">$</span>Species <span class="op">==</span><span class="st"> &quot;versicolor&quot;</span>])</span>
<span id="cb163-2"><a href="first-steps.html#cb163-2"></a>minimo_valor</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="first-steps.html#cb165-1"></a><span class="kw">print</span>(<span class="st">&quot;Max:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Max:&quot;</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="first-steps.html#cb167-1"></a>maximo_valor &lt;-<span class="st"> </span><span class="kw">max</span>(iris<span class="op">$</span>Petal.Length[iris<span class="op">$</span>Species <span class="op">==</span><span class="st"> &quot;versicolor&quot;</span>])</span>
<span id="cb167-2"><a href="first-steps.html#cb167-2"></a>maximo_valor</span></code></pre></div>
<pre><code>## [1] 5.1</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="first-steps.html#cb169-1"></a><span class="kw">print</span>(<span class="st">&quot;Versicolor:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Versicolor:&quot;</code></pre>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="first-steps.html#cb171-1"></a>especie &lt;-<span class="st"> &quot;setosa&quot;</span></span>
<span id="cb171-2"><a href="first-steps.html#cb171-2"></a>logical_for_especie &lt;-<span class="st"> </span>iris<span class="op">$</span>Species <span class="op">==</span><span class="st"> </span>especie</span>
<span id="cb171-3"><a href="first-steps.html#cb171-3"></a>petal_lengths_for_especie &lt;-<span class="st"> </span>iris<span class="op">$</span>Petal.Length[logical_for_especie]</span>
<span id="cb171-4"><a href="first-steps.html#cb171-4"></a></span>
<span id="cb171-5"><a href="first-steps.html#cb171-5"></a>true_si_mayor_que_min &lt;-<span class="st"> </span>petal_lengths_for_especie <span class="op">&gt;</span><span class="st"> </span>minimo_valor</span>
<span id="cb171-6"><a href="first-steps.html#cb171-6"></a>true_si_menor_que_max &lt;-<span class="st"> </span>petal_lengths_for_especie <span class="op">&lt;</span><span class="st"> </span>maximo_valor</span>
<span id="cb171-7"><a href="first-steps.html#cb171-7"></a></span>
<span id="cb171-8"><a href="first-steps.html#cb171-8"></a><span class="co"># Casos que cumplen ambas cosas:</span></span>
<span id="cb171-9"><a href="first-steps.html#cb171-9"></a><span class="co"># Esto es un vector lógico: true_si_mayor_que_min &amp; true_si_menor_que_max</span></span>
<span id="cb171-10"><a href="first-steps.html#cb171-10"></a><span class="co"># Puedo sumar los valores para hacer el conteo:</span></span>
<span id="cb171-11"><a href="first-steps.html#cb171-11"></a><span class="kw">sum</span>(true_si_mayor_que_min <span class="op">&amp;</span><span class="st"> </span>true_si_menor_que_max)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="first-steps.html#cb173-1"></a><span class="kw">print</span>(<span class="st">&quot;Virginica:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Virginica:&quot;</code></pre>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="first-steps.html#cb175-1"></a>especie &lt;-<span class="st"> &quot;virginica&quot;</span></span>
<span id="cb175-2"><a href="first-steps.html#cb175-2"></a>logical_for_especie &lt;-<span class="st"> </span>iris<span class="op">$</span>Species <span class="op">==</span><span class="st"> </span>especie</span>
<span id="cb175-3"><a href="first-steps.html#cb175-3"></a>petal_lengths_for_especie &lt;-<span class="st"> </span>iris<span class="op">$</span>Petal.Length[logical_for_especie]</span>
<span id="cb175-4"><a href="first-steps.html#cb175-4"></a></span>
<span id="cb175-5"><a href="first-steps.html#cb175-5"></a>true_si_mayor_que_min &lt;-<span class="st"> </span>petal_lengths_for_especie <span class="op">&gt;</span><span class="st"> </span>minimo_valor</span>
<span id="cb175-6"><a href="first-steps.html#cb175-6"></a>true_si_menor_que_max &lt;-<span class="st"> </span>petal_lengths_for_especie <span class="op">&lt;</span><span class="st"> </span>maximo_valor</span>
<span id="cb175-7"><a href="first-steps.html#cb175-7"></a></span>
<span id="cb175-8"><a href="first-steps.html#cb175-8"></a><span class="kw">sum</span>(true_si_mayor_que_min <span class="op">&amp;</span><span class="st"> </span>true_si_menor_que_max)</span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<ul>
<li>What happens if you use <code>plot()</code> with the data frame <code>iris</code>?</li>
</ul>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="first-steps.html#cb177-1"></a><span class="kw">plot</span>(iris)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<ul>
<li>If you type <code>Titanic</code> on the console you will set a data set with a not too comfortable format for analysis. Use <code>as.data.frame()</code> to convert it to a data frame and assign it to a new variable (object) in R (pick a name of your choice). Now that data frame is on memory.</li>
</ul>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="first-steps.html#cb178-1"></a>df_titanic &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(Titanic)</span></code></pre></div>
<ul>
<li>Verify that data frame is in fact a data frame.</li>
</ul>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="first-steps.html#cb179-1"></a><span class="kw">class</span>(df_titanic)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<ul>
<li>Check the classes of the data frame’s columns</li>
</ul>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="first-steps.html#cb181-1"></a><span class="kw">class</span>(df_titanic<span class="op">$</span>Class)</span></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="first-steps.html#cb183-1"></a><span class="kw">class</span>(df_titanic<span class="op">$</span>Sex)</span></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="first-steps.html#cb185-1"></a><span class="kw">class</span>(df_titanic<span class="op">$</span>Age)</span></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="first-steps.html#cb187-1"></a><span class="kw">class</span>(df_titanic<span class="op">$</span>Survived)</span></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="first-steps.html#cb189-1"></a><span class="kw">class</span>(df_titanic<span class="op">$</span>Freq)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<ul>
<li>Count (or sum) the number of people who survived and the number of people who didn’t. If you have questions about the data, type <code>? Titanic</code> to get into the help (yes! You also have help for datasets.).</li>
</ul>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="first-steps.html#cb191-1"></a><span class="kw">print</span>(<span class="st">&quot;Survived:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Survived:&quot;</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="first-steps.html#cb193-1"></a><span class="kw">sum</span>(df_titanic<span class="op">$</span>Freq[df_titanic<span class="op">$</span>Survived <span class="op">==</span><span class="st"> &quot;Yes&quot;</span>])</span></code></pre></div>
<pre><code>## [1] 711</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="first-steps.html#cb195-1"></a><span class="kw">print</span>(<span class="st">&quot;Didn&#39;t survive&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Didn&#39;t survive&quot;</code></pre>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="first-steps.html#cb197-1"></a><span class="kw">sum</span>(df_titanic<span class="op">$</span>Freq[df_titanic<span class="op">$</span>Survived <span class="op">==</span><span class="st"> &quot;No&quot;</span>])</span></code></pre></div>
<pre><code>## [1] 1490</code></pre>
<ul>
<li>Count the number of children who were on the ship.</li>
</ul>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="first-steps.html#cb199-1"></a><span class="kw">sum</span>(df_titanic<span class="op">$</span>Freq[df_titanic<span class="op">$</span>Age <span class="op">==</span><span class="st"> &quot;Child&quot;</span>])</span></code></pre></div>
<pre><code>## [1] 109</code></pre>
<ul>
<li>Count the number of men from first class.</li>
</ul>
<pre><code>## [1] 180</code></pre>
<ul>
<li>Were there any children among the crew? And women?</li>
</ul>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="first-steps.html#cb202-1"></a><span class="kw">print</span>(<span class="st">&quot;Children:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Children:&quot;</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="first-steps.html#cb204-1"></a><span class="kw">sum</span>(df_titanic<span class="op">$</span>Freq[df_titanic<span class="op">$</span>Age <span class="op">==</span><span class="st"> &quot;Child&quot;</span> <span class="op">&amp;</span><span class="st"> </span>df_titanic<span class="op">$</span>Class <span class="op">==</span><span class="st"> &quot;Crew&quot;</span>])</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="first-steps.html#cb206-1"></a><span class="kw">print</span>(<span class="st">&quot;Women:&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Women:&quot;</code></pre>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="first-steps.html#cb208-1"></a><span class="kw">sum</span>(df_titanic<span class="op">$</span>Freq[df_titanic<span class="op">$</span>Sex <span class="op">==</span><span class="st"> &quot;Female&quot;</span> <span class="op">&amp;</span><span class="st"> </span>df_titanic<span class="op">$</span>Class <span class="op">==</span><span class="st"> &quot;Crew&quot;</span>])</span></code></pre></div>
<pre><code>## [1] 23</code></pre>
</div>
</div>
</div>
<div id="extending-r-with-libraries" class="section level2" number="1.5">
<h2><span class="header-section-number">1.5</span> Extending R with libraries</h2>
<p>What we’ve seen so far belongs to what it is known as R base. When programming in R, we’ll use a set of words and symbols that the computer understands and operates according to them. But because of the complexity of the projects that are usually developed in Data Science, programming everything in R base may become verbose, difficult and the least practical way of working.</p>
<p>Several people from the R community work continously developing sets of code that, with new words and symbols, expand R and its uses. These sets of code are called libraries or packages (not only in R but in every programming language, such as Python).</p>
<p>For using a library, we employ the function <code>library()</code>, with the name of the desired library as the parameter.</p>
<p>For instance, we have seen the <code>data.frame</code> structure. If we want to build a data frame from scratch we will type <code>data.frame()</code>, with some data between the brackets. However, there are other types of <em>data frames</em> in R, which are more efficient from a couple of point of views (we will explain these during the sessions, probably). In this course, we are going to use one of these types: the <em>tibble</em>.</p>
<p><em>Tibbles</em> are redefined <em>data frames</em> and the way of building one is similar: we type <code>tibble()</code>, with the data in form of vectors inside the brackets. The problem is that if we type that directly, we’ll get an error:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="first-steps.html#cb210-1"></a><span class="kw">tibble</span>(</span>
<span id="cb210-2"><a href="first-steps.html#cb210-2"></a>  <span class="dt">my_cool_column =</span> <span class="kw">c</span>(<span class="dv">23</span>, <span class="dv">56</span>, <span class="dv">77</span>), </span>
<span id="cb210-3"><a href="first-steps.html#cb210-3"></a>  <span class="dt">my_lovely_column =</span> <span class="kw">c</span>(<span class="st">&quot;thing1&quot;</span>, <span class="st">&quot;thing2&quot;</span>, <span class="st">&quot;thing3&quot;</span>)</span>
<span id="cb210-4"><a href="first-steps.html#cb210-4"></a>)</span>
<span id="cb210-5"><a href="first-steps.html#cb210-5"></a></span>
<span id="cb210-6"><a href="first-steps.html#cb210-6"></a><span class="co"># Error...: could not find function &quot;tibble&quot;</span></span></code></pre></div>
<p>R is telling us that there is no such a function <code>tibble()</code>. In fact, there isn’t… at least in R base. There is one <code>tibble()</code> function in some other place: in one library (or several, but we’ll get into that later on).</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="first-steps.html#cb211-1"></a><span class="kw">library</span>(tibble)</span>
<span id="cb211-2"><a href="first-steps.html#cb211-2"></a></span>
<span id="cb211-3"><a href="first-steps.html#cb211-3"></a><span class="kw">tibble</span>(</span>
<span id="cb211-4"><a href="first-steps.html#cb211-4"></a>  <span class="dt">my_cool_column =</span> <span class="kw">c</span>(<span class="dv">23</span>, <span class="dv">56</span>, <span class="dv">77</span>), </span>
<span id="cb211-5"><a href="first-steps.html#cb211-5"></a>  <span class="dt">my_lovely_column =</span> <span class="kw">c</span>(<span class="st">&quot;thing1&quot;</span>, <span class="st">&quot;thing2&quot;</span>, <span class="st">&quot;thing3&quot;</span>)</span>
<span id="cb211-6"><a href="first-steps.html#cb211-6"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   my_cool_column my_lovely_column
##            &lt;dbl&gt; &lt;chr&gt;           
## 1             23 thing1          
## 2             56 thing2          
## 3             77 thing3</code></pre>
<p>Now it works. We’ll study tibbles during the sessions. The important thing to be remembered R base will not be a comfortable tool for our data science projects alone: we will need it expanded. And the way for achieving this are libraries.</p>
</div>
<div id="installation" class="section level2" number="1.6">
<h2><span class="header-section-number">1.6</span> Installation</h2>
<p><strong>Remark.</strong> The code above may not have worked in your local computer. <strong>You need to install a library before using it.</strong></p>
<p>Installing libraries (or packages: two words, same thing) is required in order to make use of them. In general, all we need to do is typing <code>install.package()</code>. Between the brackets we will include the name of library with quotation marks.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="first-steps.html#cb213-1"></a><span class="kw">install.packages</span>(<span class="st">&quot;tibble&quot;</span>)</span></code></pre></div>
<p><strong>Recommendation.</strong> Once you install a library on your computer, there is no need to do it again. It is strongly recommended to type the installation command on the console, not on your scripts, so that the library won’t be reinstalled all over again.</p>
<p><strong>Exercise.</strong> During the session, if you pay attention, we will talk about the <em>tidyverse.</em> It is a set of libraries, containing the two most important for our course: dplyr and ggplot2. Installing tidyverse, dplyr, ggplot2, tibble, readr and a lot more will also be intalled along. Install tidyverse on your computer. Remember to use the console. <em>Hint.</em> When you install a library, a lot of messages will come up on the console. Don’t worry: they are only messages, not errors. If you really read the word <code>Error</code> on the console, ask your teacher.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>

<a href="reading-data-with-readr.html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
