---
title: "Los peligros de la moralidad"
author: "Leonardo Hansa"
date: "2022-08-09"
categories: [lecturas]
---

- Twitter, como tribunal moral.
- Era de la hipermoralización. Despertar religioso sin Dios. Colapso del protestantismo ha dejado un vacío. Eric Hoffer: aunque la nuestra es una época sin Dios, es justo lo opuesto a no religiosa.
- las creencias morales son muy distintas a otros tipos de creencias.

# 1. Darwin y el origen de la moralidad

- Lo moralmente atractivo en la naturaleza humana es producto de la selección natural que aumentó el éxito reproductivo de la especie.
- nihilismo moral.b Michael ruse y Richard Joyce. Nuestras creencias morales son ilusiones útiles para regular nuestra vida social.
- no hay colores, solo longitudes de onda. No hay moral, solo actos que favorecen el éxito reproductivo.
- intentos de Kant o Dostoïevski de dar lógica a la moral han fallado. Dilema de Platón: lo bueno es bueno porque Dios lo manda o Dios lo manda porque es bueno?

# 2. Teorías evolucionistas de la moral

- El Levítico tiene más sentido si pensamos que los antiguos clasificaban los antiguos en dos temas: me da asco o me da menos asco.
- Hume: la razón es esclava de las pasiones y no puede hacer otra cosa que servirlas y obedecerlas.
- Los sentimientos Vienen primero y condicionan la manera de razonar las conclusiones (conclusiones a priori, razonamiento a posteriori).
- La moralidad no trata de cómo tratamos a otros sino de unir grupos
- Los tres grandes de la moralidad: autonomía, comunidad y divinidad.
- Un sistema moral no puede dar prioridad a las tres patas a la vez.
- Según la ética de comunidad, ls gente en los puestos de poder debería velar por subordinados y no actuar según sus propios intereses.
- Haidt: moralidad es Cualquier sistema de valores relacionados entre sí, Prácticas, instituciones y mecanismos psicológicos que trabajan de forma conjunta para regular y suprimir el egoísmo y hacer posible la vida social.
- Existe evidencia de que en sociedades de cazadores nómadas, los cazadores más fuertes tenían más hijos y más relaciones exteaconyugales.
- El daño al servicio de la cooperación puede ser moralmente bueno. O sea, la moralidad puede implicar inmoralidad.
- Teoría de la diada: un agente moral y un paciente moral.
    - Cuando se juzga algo como inmoral dado un agente, se tiende a buscar un paciente para justificar ese juicio. Es instintivo e inevitable completar la pareja.
    - Cuando alguien sufre, se busca un agente (se ha recurrido a brujas, fuerzas sobrenaturales)
- Encasillamiento moral: se categoriza a una persona como agente o paciente, no ambas. De manera permanente.
    - Estrategia habitual en abogacía es presentar como víctima a su cliente acusado.

# 3. Conceptos básicos de la psicología moral y evolucionista

- Gran parte de nuestras conductas morales son dirigidas a observadores.
- Las actitudes se enmarcan en preferencias personales (gustos, mar o montaña), convenciones (normas, conducir por la izquierda en UK) o imperativos morales (principios, el aborto está mal).
    - Las creencias morales involucran a todos los demás.
- **Mandato moral:** actitud con convicción moral
    - Universales
    - Objetividad
    - Autonomía
    - Emociones
    - Motivación y justificación
    - Intolerancia
    - Inoculación contra la obediencia a autoridades
    - Barrera para resolución de conflictos
    - Activismo/violencia
    - La moralidad bate a la justicia
- las personas son influenciables y tienden a seguir a mayorías (Asch, Cialdini)
- las personas con convicciones morales tienden a votar más y a Implicarse en política porque ven como una obligación enfrentarse al problema moral que perciben.
- Las convicciones morales no se votan (conflicto democrático)
- la reciprocidad indirecta hace esencial al cotilleo.
- En casos de reciprocidad indirecta conocida, la ayuda no es un acto altruista, sino una inversión en reputación.
- Además, no ayudar a alguien categorizado a todos como malo no es malo.
- Tendemos a atribuir virtudes a personas en lugar de a actos.
- estímulo supernormal: versión exagerada de un estímulo. Puede incitar el ataque o la protección en algunas especies. En humanos, alimentos artirficiales zucarados, o exceso de chocolate, pornografía, implantes, programas de cotilleo, redes sociales
- moralización : adquisición de cualidades morales por parte de objetos o acciones moralmente neutras (el tabaco se ha moralizado y la homosexualidad de está desmoralizando)
- la moralización es progresiva. Primero cubre a psrte grande la Población y luego entra en juego el gobierno e instituciones.
- La medicina se está entrelazando cada vez más con valores sociales y sistemas morales (pareja enfermedad/pecado)
- dos tipos de agresión: proactiva y reactiva
    - Es más probable que los proactivos reincidan, que sean psicópatasy es menos probable que respondan a fármacos.
    - hay estudios en no humanos que apoyan que hay diferencia que ambos tipos tienen bases neuronales, hormonales y genéticas diferentes.
    - parece que hemos evolucionado a una baja propensión a la reactiva y una alta a la proactiva.
- La gente que hace cosas malas rara vez cree que está haciendo algo malo (Baumeister). Pueden incluso sentirse víctimas.
- hay víctimas que juegan un papel en su propio ataque
- la violencia y la crueldad tienen cuatro causas: ambición, avaricia, alta autoestima e idealismo moral.
- la religión no es un problema sino la fe (en dios, en el comunismo, en nacionalismos)
- es más fácil matar (incluso cara a cara) cuando la víctima ha sufrido la muerte social.
- la muerte social puede darse por tres cosas: pensamiento ellos/nosotros, deshumanización de las víctimas o culpar a las víctimas
- si descategorizamos, pondremos frenos al mal.
- Lo mekor y lo peor de nosotros proviene de ver a los demás como humanos.

# 4. La división ellos/nosotros y el tribalismo moral

- hipótesis del altruismo parroquial. La guerra pudo haber extendido el altruismo entre la humanidad. La cooperación entre humanos surgió para derrotar a los humanos de otro grupos.
- sentimos menos empatía por individuos de grupos diferentes al nuestro
- la schadenfreude se asocia a circuitos de recompensa del sistema nervioso
- estar a favor une menos que estar en contra. Es mayor el placer por las pérdidas del rival que por ganancias propias.
- A partir de los 3 meses los niños ya muestran sesgos contrarios a personas de otro grupo étnico.
- La aversión a la violencia disminuye cuando se realiza contra grupos políticos contrarios.
- Tendemos a querer pertenecer a un grupo. Para eso, estamos dispuestos a aceptar cualquier creencia, por rara que sea.
- Si se llega con los rivales a un acuerdo, ese tema deja de tener interés moral. Por eso se moralizan temas nuevos.
- Cuanto más apartadas estén las creencias de verdades neutrales, mayor será la sensación de coalición. Comunicar verdades neutrales no sirve como señal diferencial.
- un grupo identificado por una creencia no podrá cambiar su punto de vista sobre esa creencia pero sí sobre otras (si te define ser de un equipo de fútbol, te dará igual cambiar tu postura sobre el calentamiento global).

+ Esto afecta especialmente a grupos en torno a cuestiones científicas (ya que nunca podrán falsarlas)

- dos tipos de creencias: funcionales y sociales. Es como los empleados en empresas, que algunos están enchufados. O la ropa, que alguna te la pones solo por encajar.
- Las creencias sociales se pueden adoptar para postureo, o adular a alguien, o sentirse superior.
- Tenemos creencias irracionales porque tenemos recompensas sociales por esas creencias.
- El alejamiento de la racionalidad no se debe a una irracionalidad en términos lógicos, sino a una búsqueda en función de nuestro interés social. Para combatir creencias, no se puede aplicar la lógica sino entender la función social de esas creencias.
- El contenido de una creencia es menos importante que el que todos los miembros crean lo mismo: que todos coincidan en el tema es lo que los une.
- Las mentiras pueden ser señal de lealtad, si sirven para promulgar que se apoya al grupo.
- No solo los nazis aplicaban una moral distinta a los suyos (los arios) y los demás. Las religiones lo hacen, los nacionalismos lo hacen. Actualmente, la ideología política influye también. En EEUU, las encuestas muestran que los partidarios de un partido (66%) defienden la violencia contra los del otro.
- La polarización política no solo afecta a la definición de valores morales, sino a la percepción de la propia realidad.
- Una parte importante de la identidad propia es contra quién estamos. Si no tenemos un enemigo (como cuando EEUU perdió a la URSS), hará falta inventarse algo nuevo (como grupos internos)
- La ausencia de religión entre gente de izquierdas y ateos los está llevando a construir rituales basados précisément en religión.
- En las sociedades de cazadores no hacen falta las ideologías para detectar a desleales dentro del grupo: los sistemas eran simples y se detectaban mediante las acciones, no las creencias.
- La división ellos nosotros se ha podido combatir en experimentos poniendo a la gente a trabajar en una misma tarea.

# 5. La moralidad en el mundo moderno

- Cultura del honor hasta siglo XIX. Sensible al insulto, se considera ataque a la reputación, se soluciona agresivamente. Hay una estructura legislativa débil. Siglo XX, cultura de la dignidad. El insulto se pasa por alto, no afecta a la reputación. Siglo XXI, cultura del victimismo. El insulto afecta pero se acude a terceras personas.
- Ser víctima da una categoría moral más alta.
- Ideología política como método de atracción sexual. El beneficio económica y político de alardear de postura política es nulo actualmente. Pero tiene interés sexual y social.
- El exhibicionismo moral consiste en alardear de ser superior moralmente. Una forma de hacerlo es inventarse problemas morales donde otros no los ven. El exhibicionismo es malo moralmente porque aumenta el cinismo, agota el agravio (Pedro y el lobo) y favorece la polarización de grupo.
- Hace poco las palabras eran violencia. Ahora, el silencio (ante determinados temas) también es violencia.
- Todo se está moralizando (comer carne, ir en coche) y la consecuencia es que la gente teme decir lo que piensa o hace (por miedo a herir o por miedo a que lo cancelen).
- Una de las razones de esta dictadura de virtud (independiente del Estado) es la ausencia de religión. El papel de los medios es clave: muestran cambios que observan en pequeños grupos, y el resto de grupos con el tiempo absorbe estos cambios. Los medios transmiten lo que observan y, como consecuencia, contaminan.
- Además, los conflictos venden más que las relaciones pacíficas (tanto medios de comunicación como en ficción).
- La falacia del mundo justo: tendemos a pensar que el mundo reparte justicia automáticamente y, si a alfuien le ocurren cosas malas, será por algo. O sea, se culpa a la víctima. Ocurre con violaciones, en situaciones financieras, en salud.
- Se puede moralizar por egoísmo (por mi bien) o altruismo (bien común). Pero parece que se tiende más a lo primero.
- La Biblia (Carel van Schaik y Kai Michel) pudo surgir como una guía moral para una sociedad agrícola que se enfrentaba a situaciones no conocidas para los cazadores. El sedentarismo cambió la sociedad: desigualdad social, guerras a mayor escala y epidemias. Los grupos nómadas eran menos sensibles a epidemias por estar menos expuestos a contaminaciones y, por su menor tamaño, era más difícil que las propagaran.
    - En el monoteísmo, como no hay dioses malignos, Dios envía plagas a los pecadores. O sea, las enfermedades son el castigo contra la inmoralidad.
    - además, la religión provee de recomendaciones de comportamiento anti enfermedades (evitar a enfermos, trato con extraños, enterramiento, nutrición).
- Los antiguos no conocían los microbios, pero contra las epidemias idearon un sistema de protomedicina.
- con la covid hemos copiado comportamientos religiosos: idealización del lavado de manos, moralizacion del uso de mascarilla y culpabilizacion de los enfermos.

# 6. La nueva religión de la justicia social crítica

- Posmodernismo en la mitad del s. XX. Lleva al nihilismo más adelante. De filosofía se pasa a ideología. Finalmente se acepta que si hay una verdad, una verdad moral narrada por los victimismos.
- La justicia social crítica surge en ambientes no religiosos, con comportamientos similares a los de los protestantes.

# 7. Los peligros y problemas de la moralidad

- Problema 1. Cuando conflicto se convierte en moral es más difícil llegar a acuerdos.
    - Si yo creo que un problema es moral, no sólo yo voy a evitar caer en él sino que quiero que tú no caigas en él. Si me creo en posesión de la verdad moral, me creo con el deber de limitar tus derechos.
- Problema 2. Las sociedades morales tienden al autoritarismo, la jerarquía, el elitismo y la desigualdad.
    - En el pasado L moralidad se ha usado para justificar que lo que hacen las clases altas es lo bueno y lo de las clases bajas, lo malo.
- Problema 3. La moralidad promueve las guerras y los genocidios
    - La moralidad pone al Nosotros por encima del Yo, pero también al Nosotros por encima del Ellos. O sea, promueve la cooperación pero también la competición.
- En muchas ocasiones se considera que la violencia es lo correcto (violencia moralista)
- La única forma de acabar con la violencia (salvo la de psicópatas y casos extremos) es convertirla en inmoral.
- La moralidad puede ser un problema ante la ciencia, si los avances de esta atentan contra los principios de la otra.
- Propuestas para evitar caer es simplificaciones morales de buenos y malos:
    - Aumentar el sentimiento de humanidad, destacar lo que nos une.
    - Aumentar contacto con personas de otros grupos.
    - Implicar a diferentes grupos en objetivos comunes.
    - Los líderes y medios de comunicación deberían dar ejemplo pero promueven el conflicto.
- El peligro de la moralidad en la ciencia es que el código binario de esta (verdadero/falso) no es compatible con el de aquella (bueno/malo).
- El deseo de ser considerados buenos es más fuerte que el deseo de encontrar la verdad. Por eso la moral es más fuerte que la ciencia.

# 8. El futuro de la moralidad

- En el ámbito político necesitamos abandonar los discursos de Buenos y malos en los conflictos.
- En filosofía se pueden buscar normas en favor de la cooperación saltando la moralidad como herramienta para ello.
- Las RRSS deberían cambiarse para no promover la pelea moral.

# Léelo

- [Versión papel.](https://amzn.to/3A90QTr) 
- [Versión kindle.](https://amzn.to/3dckAwp)


