---
title: "Diferencia de edad entre parejas sentimentales en películas"
description: "Buenas diferencias de edades entre parejas en películas"
description-meta: "Exploración de datos de películas"
author: "Leonardo Hansa"
date: "2023-02-19"
categories: [exploraciones]
execute: 
  echo: false
---

El [tidytuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-02-14/readme.md) del 14 de febrero de 2023 trae datos de diferencias de edad entre parejas sentimentales en películas de Hollywood. 


```{r}
#| label: reading
#| echo: false
#| message: false
library(readr)
library(dplyr)
library(ggplot2)
library(stringr)
age_gaps <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-02-14/age_gaps.csv')
```

Diferencia de edad en las 40 películas con más diferencia: 

```{r}
#| label: df-plot-1
df_plot_1 <- age_gaps |> 
  slice_max(age_difference, n = 40)

ggplot(df_plot_1) + 
  geom_linerange(
    aes(
      y = reorder(movie_name, actor_1_age), 
      xmin = actor_1_age, 
      xmax = actor_2_age
    )
  ) + 
  labs(x = "", y = "")
```

Las décadas con mayor diferencia son las que menos muestra tienen.

```{r}
age_gaps |> 
  mutate(decada = str_extract(as.character(release_year), "\\d\\d\\d"), 
         decada = str_c(decada, "0")) |>
  ggplot() + 
  geom_boxplot(aes(x = decada, y = age_difference)) +
  geom_jitter(aes(x = decada, y = age_difference), alpha = 0.3, width = 0.25) +
  labs(x = "", y = "", 
       title = "Distribución de la diferencia de edad entre personajes de películas, por década")
```
Selecciono las 40 películas con más diferencia relativa con respecto al actor más joven. 

```{r}
#| label: plot-2
age_gaps_filtered <- age_gaps |> 
  mutate(age_difference_rel = age_difference / actor_2_age) |> 
  with_groups(movie_name, ~ filter(.x, n() == 1))

ggplot(slice_max(age_gaps_filtered, age_difference_rel, n = 40), 
       aes(x = reorder(movie_name, actor_1_age))) + 
  geom_point(aes(
    y = actor_1_age,
    col = character_1_gender  
  )) + 
  geom_point(aes(
    y = actor_2_age, 
    col = character_2_gender  
  )) + 
  geom_linerange(aes(
    ymin = actor_2_age, 
    ymax = actor_1_age
  )) + 
  coord_flip() + 
  labs(x = "", y = "") + 
  scale_color_discrete("Personaje")
```

<!-- artists <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-17/artists.csv') -->


<!-- cats_uk <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-31/cats_uk.csv') -->
<!-- cats_uk_reference <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-31/cats_uk_reference.csv') -->

