---
title: ""
description: ""
description-meta: ""
author: "Leonardo Hansa"
date: "2023-10-25"
categories: [datos]
execute: 
  echo: false
freeze: auto
---

He descargado los datos de la encuesta salarial del INE. 

```{r}
#| label: libs
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)

ggplot2::theme_set(theme_light())
```

```{r}
#| label: read-data
df_salarios <- read_csv2("data/28191.csv", locale = locale(encoding = "latin1"))

df_salarios <- janitor::clean_names(df_salarios)
```

```{r}
#| label: process-total

df_salarios <- df_salarios |> 
  mutate(
    medidas_y_percentiles = janitor::make_clean_names(medidas_y_percentiles, 
                                                      allow_dupes = TRUE)
  )


df_total <- df_salarios |> 
  filter(comunidades_autonomas == "Total Nacional")

df_total <- df_total |> 
  rename(total_nacional = total) |> 
  select(-comunidades_autonomas)

df_salarios <- df_salarios |> 
  filter(comunidades_autonomas != "Total Nacional")

df_salarios <- df_salarios |> 
  mutate(comunidades_autonomas = case_when(
    str_detect(comunidades_autonomas, "Madrid") ~ "Madrid",
    str_detect(comunidades_autonomas, "Balears") ~ "Baleares",
    str_detect(comunidades_autonomas, "Asturias") ~ "Asturias",
    str_detect(comunidades_autonomas, "Navarra") ~ "Navarra", 
    TRUE ~ comunidades_autonomas
  ))
```

```{r}
df_salarios |> 
  pivot_wider(names_from = medidas_y_percentiles, values_from = total) |> 
  ggplot(aes(x = periodo)) +
  geom_ribbon(aes(ymin = cuartil_inferior, ymax = cuartil_superior), 
              fill = "#800080", alpha = 0.3) + 
  geom_line(aes(y = mediana), color = "#800080") + 
  facet_wrap(~comunidades_autonomas) + 
  labs(
    x = "", y = "Salario", 
    title = "Evolución del salario en España por comunidades autónomas",
    subtitle = "Mediana y cuartiles", 
    caption = "Fuente: INE"
  )


  
```


